### ISSUE TITLE
Improve exception reporting

### ISSUE THREAD

**Issue by charphi** [amattioc/SDMX#104]
Currently, there is only one exception type (SdmxException) for any problem that might occur.
Sometimes, it is difficult to pinpoint the origin of a problem because it is hidden behind several layers of SdmxException.

I think this could be improved by separating I/O exception from business or api exceptions.
For example: "connection failure" vs "No results matching the query"

What do you think about adding IOException (in complement of SdmxException) to the methods in GenericSDMXClient ?

**Comment by amattioc** [comment]
Yes it can be a good idea.

**Comment by charphi** [comment]
Currently, every methods of `GenericSDMXClient` throw `SdmxException`.
Every other exception types are swallowed by `SdmxException`.

I think we could improve this situation by using specialized exceptions in a small hierarchy with a single root. We could distinguish exceptions coming from connection (io), common xml parsing, specific sdmx-ml parsing and restful ws responses.

Here are two possible solutions:

1. Using `IOException` as base:
  - `IOException`
    - `SdmxResponseException`
    - `SdmxParsingException`
    - `SdmxXmlException`
  
2. Using SdmxException as base:
  - `SdmxException`
    - `SdmxResponseException`
    - `SdmxParsingException`
    - `SdmxXmlException`
    - `SdmxIOException`

What do you think about it?

**Comment by amattioc** [comment]
Hi @charphi,

I prefer the second option, but I would like to change the name of the **SdmxXmlException** to **SdmxXmlContentException**. So, to summarize:

  - `SdmxException`
    - `SdmxResponseException`
All exceptions that are related to one of the typical SDMX errors (see REST specs)
    - `SdmxParsingException`
All exceptions thrown by XML parsing libraries
    - `SdmxXmlContentException`
All semantic errors contained in the response XML (even if the XML itself is sintactically correct)
    - `SdmxIOException`
All exceptions that are related to connection and IO 

What about that?

Best, Attilio

**Comment by charphi** [comment]
Seems ok; I would just rename `SdmxParsingException` as `SdmxXmlParsingException` to be consistant.

**Comment by amattioc** [comment]
Ok, I agree.

  - `SdmxException`
    - `SdmxXmlParsingException`
All exceptions thrown by XML parsing libraries
    - `SdmxXmlContentException`
All semantic errors contained in the response XML (even if the XML itself is sintactically correct)
    - `SdmxIOException`
All exceptions that are related to connection and IO 
    - `SdmxResponseException`
All exceptions that are related to one of the typical SDMX errors (see REST specs)

**Comment by amattioc** [comment]
Hi @charphi @eivindveg, this refactoring should be in line with what we discussed in #104 and #116. We'll be happy to receive your feedback...

**Comment by eivindveg** [comment]
Reviewing. Will be adding comments and questions as I go. The new inheritance tree for SdmxExceptions now seems very extensive. Maybe a bit overkill, but that's always better than the opposite in my opinion. Cause initialization as per #116 looks good, especially when it comes to the different types of IO errors.

**Comment by eivindveg** [comment]
Commented at one place that the throws clause may be a bit too generalized based on what is actually thrown(declares throws SdmxException, only actually throws SdmxInvalidParameterException). This seems to be happening multiple places.

In these cases, I feel that even if two different SdmxExceptions are thrown, both of these should be explicitly declared instead of a forced general catch. If both are declared instead of the base class, all three of these try catch blocks are valid:

## General catch
```
try {
   // do something
} catch (SdmxException e) {
  // handle
}
```
## Explicit catch
```
try {
   // do something
} catch (SdmxInvalidParametersException e) {
  // handle
} catch (SdmxIOException e) {
  //handle
}
```
## Multi-catch
```
try {
  // do something
} catch (SdmxInvalidParametersException | SdmxIOException e) {
  // handle
}
```

All this may not be necessary for a specialized library such as this, and is probably intended for general purpose libraries, so I'm not going to raise a fuzz if you disagree. :)

**Comment by charphi** [comment]
It seems ok to me.
