### ISSUE TITLE
Connection failed. HTTP error code : 404, message: Not Found

### ISSUE THREAD

**Issue by AmrTealeb** [amattioc/SDMX#105]
I run the tool on UN data and select values from different dimensions but when i click "Check Query" i get the following exception
"Exception. Class: it.bancaditalia.oss.sdmx.util.SdmxException .Message: Connection failed. HTTP error code : 404, message: Not Found
SDMX meaning: No results matching the query."

**Comment by amattioc** [comment]
Hi @AmrTealeb,
this typically means that the query has no active  results. Can you try a different combination of codes for the dimensions?

**Comment by amattioc** [comment]
Hi @AmrTealeb ,
any updates on this issue?

**Comment by amattioc** [comment]
Hi @AmrTealeb ,
I assume the problem was solved. In case you need help you can reopen.

Regards.
