### ISSUE TITLE
Stata - Errors trying getdata

### ISSUE THREAD

**Issue by Samuel-P-R** [amattioc/SDMX#106]
Hi,

We have been trying the getdata function in Stata. However we are experiencing an issue with sources like EUROSTAT, ECB but not the IMF or the OECD.

The error is generic : ERROR: No data matched the query specified. Please check the query by running: getdatacodes
Data is available via the SDMX Rest url.
The UI (getdatacodes) returns the following error :
 Exception. Class: it.bancaditalia.oss.sdmx.util.SdmxException .Message: Exception. Class: it.bancaditalia.oss.sdmx.util.SdmxException .Message: Exception. Class: java.net.ConnectException .Message: Connection refused: connect

Do you have an idea of the reason of this issue ?

**Comment by amattioc** [comment]
Hi,

The getdata module is not part of this project, so I cannot be very specific. Anyway the problem could be related to queries that do not contain results in the providers. 

For the ECB could you try requesting EXR.A.USD.EUR.SP00.A ? 

At the stata page of the wiki (https://github.com/amattioc/SDMX/wiki/SDMX-Connector-for-STATA) you can find more examples of working queries. You'll also find the instructions for starting the sdmx  helper, that will guide you in building meaningful queries for every provider.

Let me know.

**Comment by Samuel-P-R** [comment]
Dear Attilio,

There was actually a bug in the SDMX connector that has been fixed.
Thanks for your help,

S.

**Comment by amattioc** [comment]
Great, I'll close the issue then.

Best, Attilio
