### ISSUE TITLE
configuration for INSEE provider

### ISSUE THREAD

**Issue by RemyArnaud** [amattioc/SDMX#109]
Dear Mister,

I first want to thank you for this useful tool you have created. As I collect data from French INSEE organization, I've tried to configure the excel version of your tool, but my computer skills are too light to succeed. Is there an "illustred" "step by step" example of how to configure the tool for excel? It would be great.

Best reguards

Rémy Arnaud

**Comment by amattioc** [comment]
Dear Rémy, 
the code of the excel connector could be used in many different ways (e.g. adding a workbook macro, creating an excel add-in etc.). In the wiki I did not want to get into detailed explanations of this part because the steps are very related to the goal and to the excel version in use.  

Probably the easiest way to use the **.bas** file of the connector is by importing a new macro in a single workbook. You can find some step-by-step guides by simply googling "import excel macros". As an example, this is one of the results that I got: https://www.youtube.com/watch?v=Z6Z-gKxyH3U

Once these steps are done, you'll probably just need to add a new environment variable to you PC, pointing to the SDMX.jar file. 

Please let me know if I can help more...

Best, Attilio

**Comment by RemyArnaud** [comment]
Dear Attilio,

Thanks for your answer!
I think i've succeeded to import the macro in Excel (I'll check with the
vidéo tonight because youtube is blocked on my professionnal network).

I don't want to waste your time, but pointing to the SDMX.jar file is
written like that in the macro? :
"
 Dim SDMX_JAVA As String
    Dim SDMX_LIB As String

    SDMX_JAVA = Environ("SDMX_JAVA")
    If SDMX_JAVA = "" Then
       SDMX_JAVA = "java"
    End If

    *SDMX_LIB =
Environ("C:\Users\ARNAUD\Desktop\CdG\Macros\SDMX-1.6.2\RJSDMX\inst\java\SDMX.jar")*
    If SDMX_LIB <> "" Then
       SDMX_LIB = "-cp " & SDMX_LIB
    End If
"
As you can see, I'm terrible in computer languages...

Reguards.

Rémy

2016-08-31 10:53 GMT+02:00 Attilio Mattiocco <notifications@github.com>:

**Comment by amattioc** [comment]
Hi Rémy, no problem. If you just want to hard-code the jar path in the macro you can replace the original line:

`SDMX_LIB = Environ("SDMX_LIB")`

with this:

`SDMX_LIB = "C:\Users\ARNAUD\Desktop\CdG\Macros\SDMX-1.6.2\RJSDMX\inst\java\SDMX.jar"`

Let me know, Attilio

**Comment by RemyArnaud** [comment]
Attilio,

Thank you so much for the time you spend on my case!

My macro is improving but still doesn't work...
New error message:
[image: Images intégrées 1]

My question : am I filling well the cells? I type INSEE in A1 and the
indicator I need in cell B2 and launch the macro:

[image: Images intégrées 2]

Reguards


2016-08-31 12:26 GMT+02:00 Attilio Mattiocco <notifications@github.com>:

**Comment by amattioc** [comment]
Hi Rémi, I cannot see the images you pasted. Can you paste them again using the browser?

**Comment by RemyArnaud** [comment]
Hi Attilio,

Here are the images in joint file.

And here is the macro where i've pointed the SDMX.jar file :

'/* Copyright 2010,2014 Bank Of Italy
'*
'* Licensed under the EUPL, Version 1.1 or - as soon they
'* will be approved by the European Commission - subsequent
'* versions of the EUPL (the "Licence");
'* You may not use this work except in compliance with the
'* Licence.
'* You may obtain a copy of the Licence at:
'*
'*
'* http://ec.europa.eu/idabc/eupl
'*
'* Unless required by applicable law or agreed to in
'* writing, software distributed under the Licence is
'* distributed on an "AS IS" basis,
'* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
'* express or implied.
'* See the Licence for the specific language governing
'* permissions and limitations under the Licence.
'*/

Public Sub getTimeSeries()
'## environment for system call
    Dim SDMX_JAVA As String
    Dim SDMX_LIB As String

    SDMX_JAVA = Environ("SDMX_JAVA")
    If SDMX_JAVA = "" Then
       SDMX_JAVA = "java"
    End If

    SDMX_LIB =
"C:\Users\ARNAUD\Desktop\CdG\Macros\SDMX-1.6.2\RJSDMX\inst\java\SDMX.jar"
    If SDMX_LIB <> "" Then
       SDMX_LIB = "-cp " & SDMX_LIB
    End If

    Dim ws As Excel.Worksheet
    Set ws = Excel.ActiveSheet

'## clean-up sheet
    With Sheets(ws.Name)
        .rows(2 & ":" & .rows.Count).ClearContents
    End With

'## get provider and query from cells. if not present prompt user
    Dim provider As String
    Dim query As String
    Dim startTime As String
    Dim endTime As String
    startTime = """"""  ' blank
    endTime = """"""    ' blank

    provider = ws.Cells(1, 1).Value
    query = ws.Cells(1, 2).Value
    startTime = ws.Cells(1, 3).Value
    endTime = ws.Cells(1, 4).Value
    If provider = "" Then
        MsgBox "Error: provider has not been set in cell A1. Please set it."
        Exit Sub
    End If
    If query = "" Then
        MsgBox "Error: query has not been set in cell B1. Please set it."
        Exit Sub
    End If

    ws.Cells(1, 1).Font.Bold = True
    ws.Cells(1, 2).Font.Bold = True
    ws.Cells(1, 3).Font.Bold = True
    ws.Cells(1, 4).Font.Bold = True
    ws.Cells(1, 1).Font.Color = vbRed
    ws.Cells(1, 2).Font.Color = vbRed
    ws.Cells(1, 3).Font.Color = vbRed
    ws.Cells(1, 4).Font.Color = vbRed



'## build the command
    Dim command As String
    command = "cmd /c " & SDMX_JAVA & " " & SDMX_LIB & "
it.bancaditalia.oss.sdmx.util.GetTimeSeries " _
                & " " & provider & " " & query & " " _
                & """" & startTime & """" & " " & """" & endTime & """" & "
" & user & " " & pw

'## execute the command
    Dim wsh As Object
    Set wsh = VBA.CreateObject("WScript.Shell")
    Set objExec = wsh.Exec(command)
    Dim result As String
    Dim error As String
    Dim rc As Integer
    rc = objExec.Status
    result = objExec.StdOut.ReadAll
    error = objExec.StdErr.ReadAll
    If result = "" Then
        MsgBox Right(error, 1024)
        Exit Sub
    Else
'## parse results
        'MsgBox result
        Dim rows As Variant
        rows = Split(result, vbLf, -1)
        Dim tsSize As Integer
        tsSize = UBound(rows) + 1
        Dim i As Integer
        i = 0
        Do While i < tsSize
            Dim fields As Variant
            fields = Split(rows(i), ";", -1)
            Dim fieldSize As Integer
            fieldSize = UBound(fields) + 1
            Dim j As Integer
            j = 0
            Do While j < fieldSize
                Dim n As Integer
                Dim m As Integer
                n = 2 + i
                m = 1 + j
                ws.Cells(n, m).Value = fields(j)
                j = j + 1
            Loop
            i = i + 1
        Loop
    End If
End Sub


Thanks a lot for your help!

Rémy


2016-08-31 13:53 GMT+02:00 Attilio Mattiocco <notifications@github.com>:

**Comment by amattioc** [comment]
Hi Rémi, the images are not available. Can you paste them in the issue comments (https://github.com/amattioc/SDMX/issues/109) using the browser?

**Comment by RemyArnaud** [comment]
OK, here are the images, hope it's working:
![2016-08-31 14_01_31-microsoft excel - test_insee](https://cloud.githubusercontent.com/assets/21340009/18129345/aa387926-6f8a-11e6-961f-f56101383aa3.jpg)
![2016-08-31 14_02_29-microsoft excel - test_insee](https://cloud.githubusercontent.com/assets/21340009/18129347/ad900e86-6f8a-11e6-9d9b-b1cdd9080b1b.jpg)

**Comment by amattioc** [comment]
Hi, the content of cell **B1** is not a sdmx valid query for INSEE. Try using this code for a start:

`IPI-1990-CPF3/29-7.CVS-CJO`

It should match the time series: **Indice CVS-CJO de la production industrielle, base 1990 - Appareils domestiques (NES C44, CPF 297) - Série arrêtée**.  

Do you see any results?

**Comment by RemyArnaud** [comment]
WOW! Work great!!! It's really usefull to update indicators instead of typing it manually!
I'm going to turn my indicators "names" in SDMX code.

Many many thanks for your work!

**Comment by amattioc** [comment]
You're welcome. 

For the conversion into sdmx codes you may find the sdmx helper useful. If you want to try it, just double click the SDMX.jar file and it should start.

Best, Attilio

**Comment by RemyArnaud** [comment]
OK! now I understand why there is this tool!

Thanks again!

**Comment by boujniba** [comment]
Hello amatioc,
I have de same probleme with the excel vesipn!!

![erreur](https://cloud.githubusercontent.com/assets/22006660/18250140/69b8cb70-7382-11e6-8522-01a81285528d.jpg)


Best Regard.

T.R

**Comment by amattioc** [comment]
Hi @boujniba 
are you running the connectors from behind a proxy? The error is typically associated to that situation.

Best, Attilio

**Comment by boujniba** [comment]
think you for your response.

I use the .bas file of the connector by importing a new macro in a single workbook and i run F5.

Many thanks.
T.R

**Comment by amattioc** [comment]
Hi, the way you use the macro is correct. Anyway I need to know if you are running it in an environment (e.g. inside a corporate network) where there is a proxy between your computer and the public network. You could check this with your local IT support.

Best, Attilio

**Comment by boujniba** [comment]
I run macro in corporate netwotk (proxy).

T.R

**Comment by amattioc** [comment]
Ok, in this case you have to set the proxy info in the sdmx configuration file (https://github.com/amattioc/SDMX/wiki/System-Configuration#network-settings).

1. you can use this template file as a reference: https://github.com/amattioc/SDMX/blob/master/JAVA/configuration.properties

2. uncomment the line:
`#http.proxy.default = hostname:port`
and set the appropriate proxy hostname and port

3. in windows, create a new environment variable, named **SDMX_CONF**. Its value has to be the fully qualified path to the configuration file (e.g: **C:\SDMX\configuration.properties**)

Remember to restart Excel after creating the environment variable, otherwise it will not be picked up by the excel environment.

It should be all, please let me know if it works.

Best, Attilio

**Comment by boujniba** [comment]
Many thanks Attilio.

T.R

**Comment by amattioc** [comment]
You're welcome.
