### ISSUE TITLE
Does ILO server work?

### ISSUE THREAD

**Issue by pdgilbert** [amattioc/SDMX#11]
I have not been able to get anything from ILO:
require("RJSDMX")
>  z <- getFlows('ILO') 
Using central configuration: /home/paul/.SdmxClient
Dec 05, 2014 11:05:16 AM it.bankitalia.reri.sia.sdmx.client.RestSdmxClient runQuery
SEVERE: Connection failed. HTTP error code : 502, message: Bad Gateway

Error in .jcall("RJavaTools", "Ljava/lang/Object;", "invokeMethod", cl,  : 
  it.bankitalia.reri.sia.util.SdmxException: Connection failed. HTTP error code : 502, message: Bad Gateway
>  tts <- getSDMX("ILO", 'EAP_TEAP_SEX_AGE_NB.AUS.*.*.*')
Dec 05, 2014 11:20:31 AM it.bankitalia.reri.sia.sdmx.client.RestSdmxClient runQuery
SEVERE: Connection failed. HTTP error code : 404, message: Not Found
SDMX meaning: No results matching the query.
Error in .jcall("RJavaTools", "Ljava/lang/Object;", "invokeMethod", cl,  : 
  it.bankitalia.reri.sia.util.SdmxException: Connection failed. HTTP error code : 404, message: Not Found
SDMX meaning: No results matching the query.
>

**Comment by amattioc** [comment]
Thanks to the great help of the ILOSTAT support I could find a workaround for this problem. A definitive fix is coming, but in the meantime the getflows already works.

6d7ba78ba310a86e998fe25d10940a07871b653e
