### ISSUE TITLE
Update IMF endpoint to http://dataservices.imf.org/REST/SDMX_XML.svc/

### ISSUE THREAD

**Issue by altomani** [amattioc/SDMX#110]
There is a new endpoint for IMF data, namely:  http://dataservices.imf.org/REST/SDMX_XML.svc .

This is a REST SDMX 2.0 service, the documentation is available at: http://datahelp.imf.org/knowledgebase/articles/838041-sdmx-2-0-restful-web-service .

A good reason for switching to this new endpoint (or possibly adding it as an alternative to the current one) is that there is much more data freely available there, compared to the sdmxws.imf.org endpoint.

**Comment by amattioc** [comment]
Hi Andrea, thanks for the info. I had a quick look at the provider and it seems interesting. I'll add it to the default list asap.

Best, Attilio

**Comment by amattioc** [comment]
Hi, the new provider has been added in commit  5ed5749. For now I called it IMF2, but the name could change. 

Best, Attilio

**Comment by altomani** [comment]
Thank you! I have tried several queries today and it appears to work perfectly.
Best,
Andrea

**Comment by amattioc** [comment]
Great. Thanks again for your hint.
