### ISSUE TITLE
Unemployment rate – statistical back-recalculation since IV 1992 – regional level series not found on ISTAT

### ISSUE THREAD

**Issue by enikogabor** [amattioc/SDMX#115]
Hi @amattioc ,

I was unable to find the “Unemployment rate – statistical back-recalculation since IV 1992 – regional level” series  in the list of flows from ISTAT. Would you please provide me information whether the above series can be accessed using the SDMX tool?

Thank you,
Eniko

**Comment by amattioc** [comment]
Dear @enikogabor, I sent an e-mail to the colleagues in ISTAT asking for information about this dataset and how to find it in the Single Exit Point. I'll keep you posted.

Best, Attilio

**Comment by enikogabor** [comment]
Thank you very much!

Best,
Eniko

**Comment by amattioc** [comment]
Hi @enikogabor,

The data flow id is  **151_140**. If you are looking for regional data this is an example of query for Tuscany and Latium:

```
R COMMAND:
result = getTimeSeries('ISTAT', '151_140/....ITE4+ITE1....');

MATLAB COMMAND:
result = getTimeSeries('ISTAT', '151_140/....ITE4+ITE1....');

SAS COMMAND:
%gettimeseries(provider="ISTAT", tsKey="151_140/....ITE4+ITE1....", metadata=1);

STATA COMMAND:
getTimeSeries ISTAT 151_140/....ITE4+ITE1.... "" "" 0 0

URL:
http://sdmx.istat.it/SDMXWS/rest/data/IT1,151_140,1.0/....ITE4+ITE1....
```

Best, Attilio

**Comment by enikogabor** [comment]
Hi @amattioc,

Yes, it works now.
Great, thank you very much.

Best,
Eniko
