### ISSUE TITLE
API Key authentication

### ISSUE THREAD

**Issue by dur41d** [amattioc/SDMX#122]
Hi,

I'm trying to connect to the UNESCO SDMX REST API which requires an API key to be supplied in the header or as a query string parameter. Does the connector support this?

Thanks

**Comment by vpinna80** [comment]
Thank you for your recommendation. ATM Unesco provider connector is not implemented; you would have to try to add it using an implementation of yours and register it with SDMXClientFactory.createClient(). However we would be happy to consider implementing it in the near future; in order to achieve this, may you link the UNESCO specification pages, please?

Thank you

**Comment by amattioc** [comment]
Hi @dur41d , 

we have a UIS provider (endpoint: http://data.uis.unesco.org/RestSDMX/sdmx.ashx/GetDataStructure/ALL), but it seems a public provider that requires no authentication. 
Can you add some more information about the endpoint and/or about the key that should be supplied? If the mechanism not supported with the current implementation we'll be happy to develop an enhancement (if it is feasible).

Best, Attilio

**Comment by dur41d** [comment]
Hi Attilio,

Thanks for the prompt response. In fact, the UIS has released a new API that is SDMX REST 2.1 compatible. More information can be obtained from https://apiportal.uis.unesco.org/ and the 'Getting Started' guide explains how get and use the API key and obtain the WADL/Swagger definitions. 

You can specify the API key either in the HTTP header using 'Ocp-Apim-Subscription-key' header name, or in the URL as a query string parameter using the 'subscription-key' parameter name.

It would be nice if you can update the 'UIS' provider to point to the new endpoint. 

I'm the technical lead for this project so please let me know if I can help.

Thanks,
Duraid

**Comment by amattioc** [comment]
Hi Duraid,

thanks for the information, very interesting. 
I did not understand if the new API can be accessed without the API key in some cases or if the key is always mandatory. I need to know it for better shaping the new connector.

Thanks a lot, Attilio

**Comment by dur41d** [comment]
Hi Attilio, the key is mandatory. If you think you can update the built in
connector soon then please let me know by when because we are conducting
training sessions in January on how to use it new api and it will be good
to also present your tools.

Thanks,
Duraid

**Comment by amattioc** [comment]
Hi Duraid, I think the new built-in provider will be available by the end of next week.
I'll add the instructions on how to configure the api key in this issue and in the wiki.

Best, Attilio

**Comment by dur41d** [comment]
That's great! Many thanks Attilio.

**Comment by amattioc** [comment]
Hi Duraid, the updates have been committed in 17310d0 

The new UIS provider will prompt for the API key the first time it is queried in a new session. If the user wants to avoid this interactive step, he can set the key statically in the configuration file using the new parameter: **uis.api.key** 

I will update the wiki with the new configuration key and the links about the UIS provider. 

We'll be happy to receive your feedback.

Best, Attilio

**Comment by dur41d** [comment]
Hi Attilio,

Sorry for the late reply. I came back from holidays today.

I tested the latest build using the SDMX.jar and the excel plugin and they both work as expected.

Thanks a lot for responding quickly to our request. We will train UNESCO staff next week to use it to query our API.

Best,
Duraid

**Comment by amattioc** [comment]
Hi, I'm glad to hear that. Please let us know if we can help more.

Best, Attilio

**Comment by dur41d** [comment]
Hi Attilio,

It will be helpful if you create another release that includes the jar files for Excel and STATA so that users don't have to build their own files.

Thanks,
Duraid

**Comment by amattioc** [comment]
Hi Duraid,

yes it will be bundled in v 1.7 soon.

Best, Attilio

**Comment by dur41d** [comment]
That's great. Thanks.

**Comment by amattioc** [comment]
Hi @dur41d release 1.7 in available. Best, Attilio

**Comment by dur41d** [comment]
Great. Thanks Attilio.
