### ISSUE TITLE
Queries to WITS and UNData fail

### ISSUE THREAD

**Issue by amattioc** [amattioc/SDMX#126]

**Comment by hetepsenusret** [comment]
Hello, I had similar problem with those providers. Provider's server require information about response type. If it is not set, server returns code 500. I solve this temporarly, by adding code:

`conn.setRequestProperty("Accept", "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8");`

into "RestSdmxClient" function: "runQuery" line 317

Best regards

**Comment by amattioc** [comment]
Hi @hetepsenusret, thanks for the hint. We made a very similar fix in our internal dev branch. I'll merge it soon.

Best, Attilio

**Comment by agdavydov81** [comment]
Please review 
https://github.com/amattioc/SDMX/pull/231
