### ISSUE TITLE
Configuration file settings for R

### ISSUE THREAD

**Issue by lz1nwm** [amattioc/SDMX#127]
I am behind a proxy and I can make queries with SDMX.jar with configuration.properties file in the same dir, so my proxy setup should be fine in configuration.properties. When I try it with R it doesn't work.  This is the error message that I have:

``` R
> getFlows('EUROSTAT')
Error in .jcall("RJavaTools", "Ljava/lang/Object;", "invokeMethod", cl,  : 
  it.bancaditalia.oss.sdmx.exceptions.SdmxIOException: Connection problems while talking to endpoint: Connection timed out: connect
```
I tried several options and none of them solved my problem:
- defined environment variable SDMX_CONF with value \path_to\configuration.properties ;
- to put the configuration.properties file in \RJSDMX\ ;
- to put the configuration.properties file in \RJSDMX\SDMX\ .

Could you please help me with the issue?

Thanks

**Comment by lz1nwm** [comment]
Just to let you know that I removed and reinstalled RJSDMX and now it seems that R reads configuration.properties file location from SDMX_CONF variable.

Please delete this issue if you find it useless.

**Comment by amattioc** [comment]
Hi @lz1nwm, I'm glad to hear that the problem was solved. I'll close the issue, but please reopen it if you have similar problems in the future.

Best, Attilio
