### ISSUE TITLE
Handle time series with non numeric data.

### ISSUE THREAD

**Issue by amattioc** [amattioc/SDMX#128]
Introduce support for string values in observations

**Comment by amattioc** [comment]
Done in 0fc85bc8965b5c96b0138f440e712d2e1844dcb7

**Comment by charphi** [comment]
Hi @amattioc.
Do you have an example of a non numeric time series?

**Comment by amattioc** [comment]
Hi, not in the SDMX world (at least not so far). 

The SDMX library is also used in another project (connector for Datastream Web Services) where some time series have string values (they basically represent dates).

**Comment by charphi** [comment]
Ok, thanks.
