### ISSUE TITLE
getSDMX bug in request having one empty series

### ISSUE THREAD

**Issue by pdgilbert** [amattioc/SDMX#13]
There is an error in this:
  tts0 <- getSDMX('IMF', 'PGI.CA.*.*.*.*')
[1] "Number of observations and time slots equal to zero,
   or not matching:  0   0"
  Error in FUN(X[[534L]], ...) : object 'tts' not found

This is happening in the call
  result = lapply(X = rList, FUN = convertSingleTS)
rList[[534L]] seems to have no data so (I'm guessing) in
convertSingleTS it prints the  message "Number of observations..."
and does not assign tts, but then tries to return tts.

I think you may want an empty series here, so everything else retrieved is not discarded. If not, this really should be an error message not a print statement.

**Comment by amattioc** [comment]
fixed in 17c4ba6ddefdd97181a3a42090649c9816924ee2
