### ISSUE TITLE
Trouble to Install on R 3.4

### ISSUE THREAD

**Issue by larry77** [amattioc/SDMX#130]
Hello,
I am running R 3.4 on a Debian environment and I get a segmentation fault when I try to install the package.
See for instance

     Installing package into ‘/usr/local/lib/R/site-library’
     (as ‘lib’ is unspecified)
     trying URL 'https://lib.ugent.be/CRAN/src/contrib/RJSDMX_1.7.tar.gz'
     Content type 'application/x-gzip' length 155642 bytes (151 KB)
     ==================================================
     downloaded 151 KB

    * installing *source* package ‘RJSDMX’ ...
    ** package ‘RJSDMX’ successfully unpacked and MD5 sums checked
    ** R
    ** demo
    ** inst
    ** preparing package for lazy loading
    ** help
    *** installing help indices
    ** building package indices
    ** testing if installed package can be loaded
    Segmentation fault
    ERROR: loading failed
    * removing ‘/usr/local/lib/R/site-library/RJSDMX’

    The downloaded source packages are in
	‘/tmp/RtmppkNo9a/downloaded_packages’
    Warning message:
    In install.packages("RJSDMX") 
    installation of package ‘RJSDMX’ had non-zero exit status 

Here is my sessionInfo()

     > sessionInfo()
     R version 3.4.0 (2017-04-21)
     Platform: x86_64-pc-linux-gnu (64-bit)
     Running under: Debian GNU/Linux 9 (stretch)

     Matrix products: default
     BLAS: /usr/lib/libblas/libblas.so.3.7.0
     LAPACK: /usr/lib/lapack/liblapack.so.3.7.0

     locale:
     [1] LC_CTYPE=en_GB.utf8       LC_NUMERIC=C             
     [3] LC_TIME=en_GB.utf8        LC_COLLATE=en_GB.utf8    
     [5] LC_MONETARY=en_GB.utf8    LC_MESSAGES=en_GB.utf8   
     [7] LC_PAPER=en_GB.utf8       LC_NAME=C                
     [9] LC_ADDRESS=C              LC_TELEPHONE=C           
     [11] LC_MEASUREMENT=en_GB.utf8 LC_IDENTIFICATION=C      

     attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods   base     

     loaded via a namespace (and not attached):
     [1] compiler_3.4.0 tools_3.4.0    tcltk_3.4.0   

Any idea about what the problem may be?

**Comment by amattioc** [comment]
Hi @larry77, can I ask you to try and install the package locally, after downloading it fron the CRAN? Do you see the same error?

Best, Attilio

**Comment by larry77** [comment]
Hi, unfortunately I get exactly the same error. It is hard for me to tell what the problem may be. 
It appears that some other people are having segmentation faults with other packages in R 3.4 (e.g. the xlsx package is another troublesome one for myself too).

https://stackoverflow.com/questions/44684612/rmongo-installation-fails-with-segmentation-fault-in-ubuntu

Some blame it on the 4.9 kernel, but actually even installing a previous kernel (3.x) does not help at all in my case. 

I also add some info about my java installation

     $ sudo R CMD javareconf
     Java interpreter : /usr/lib/jvm/default-java/jre/bin/java
     Java version     : 1.8.0_131
     Java home path   : /usr/lib/jvm/default-java
     Java compiler    : /usr/lib/jvm/default-java/bin/javac
     Java headers gen.: /usr/lib/jvm/default-java/bin/javah
     Java archive tool: /usr/lib/jvm/default-java/bin/jar

     trying to compile and link a JNI program 
     detected JNI cpp flags    : -I$(JAVA_HOME)/include -I$(JAVA_HOME)/include/linux
     detected JNI linker flags : -L$(JAVA_HOME)/jre/lib/amd64/server -ljvm
     gcc -std=gnu99 -I/usr/share/R/include -DNDEBUG -I/usr/lib/jvm/default-java/include -I/usr/lib/jvm     default-java/include/linux     -fpic  -g -O2 -fdebug-prefix-map=/home/jranke/git/r-backports/stretch/r-base-3.4.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c conftest.c -o conftest.o
    gcc -std=gnu99 -shared -L/usr/lib/R/lib -Wl,-z,relro -o conftest.so conftest.o -L/usr/lib/jvm/default-java/jre/lib/amd64/server -ljvm -L/usr/lib/R/lib -lR


     JAVA_HOME        : /usr/lib/jvm/default-java
     Java library path: $(JAVA_HOME)/jre/lib/amd64/server
     JNI cpp flags    : -I$(JAVA_HOME)/include -I$(JAVA_HOME)/include/linux
    JNI linker flags : -L$(JAVA_HOME)/jre/lib/amd64/server -ljvm
    Updating Java configuration in /usr/lib/R
    Done.

**Comment by amattioc** [comment]
This rJava issue could be a good starting point for investigation: https://github.com/s-u/rJava/issues/110

**Comment by larry77** [comment]
Thanks for pointing this out. It appears to be a nasty bug related to rJava + some security updates. It is really bad as it seems to impact pretty much any debian-based up to date linux distribution.

**Comment by amattioc** [comment]
Right, I'll see if I can workaround it using the .jpackage function in  different way...

**Comment by larry77** [comment]
I suppose that rJava is the root of all evil. Irony of fate, rJava does install without problems...it is everything else that depends on it that has some!

**Comment by amattioc** [comment]
Hi @larry77 when you have time, please try the latest commit. I tried to avoid using jpackage and just did the very necessary calls.

Let me know, Attilio

**Comment by larry77** [comment]
No luck.

     > require(devtools) 
     Loading required package: devtools
     > install_github(repo = "amattioc/SDMX", subdir = "RJSDMX")
     Downloading GitHub repo amattioc/SDMX@master
     from URL https://api.github.com/repos/amattioc/SDMX/zipball/master
     Installing RJSDMX
     '/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet  \
      CMD INSTALL  \
      '/tmp/RtmpfJi4Hb/devtools3a4e5a4c3231/amattioc-SDMX-cd8966c/RJSDMX'  \
      --library='/usr/local/lib/R/site-library' --install-tests 

    * installing *source* package ‘RJSDMX’ ...
    ** R
    ** demo
    ** inst
    ** preparing package for lazy loading
    ** help
    *** installing help indices
    ** building package indices
    ** testing if installed package can be loaded
    Segmentation fault
    ERROR: loading failed
    * removing ‘/usr/local/lib/R/site-library/RJSDMX’
    Installation failed: Command failed (1)

In any case, the real problem is that rJava is broken.

**Comment by amattioc** [comment]
Yes, it seems so. I added PR #132, that disables any onload stuff. You could try installing it :

`install_github(repo = 'amattioc/SDMX', subdir = 'RJSDMX', ref = 'amattioc-patch-1')`

and after installation (that I expect should be fine) enable the VM startup by hand:

`.jinit()`
`.jaddClassPath(file.path(find.package(package = 'RJSDMX'), 'java', 'SDMX.jar'))`

Just to be sure that the problem is actually related to jinit when called inside onLoad...

**Comment by larry77** [comment]
This is the situation: if I run the commands

      install_github(repo = 'amattioc/SDMX', subdir = 'RJSDMX', ref = 'amattioc-patch-1')

and then

    library(rJava)

    .jinit()
    .jaddClassPath(file.path(find.package(package = 'RJSDMX'), 'java', 'SDMX.jar'))

there is no error message, but if I then try to carry on by running a query via RJSDMX, then I have again a segmentation fault...

**Comment by larry77** [comment]
I have just received an update of the latest kernel for debian stretch (stable distribution).
The problem with rJava and RJSDMX appears to have been fixed.
I will run some tests tomorrow, but it looks like we are almost done here.

**Comment by amattioc** [comment]
Great. I'll be waiting for news.

**Comment by larry77** [comment]
Hello,
Well, right now everything appears to work on my machine with RJSDMX from CRAN. For this reason, Ia am closing the issue now.

**Comment by amattioc** [comment]
Hi @larry77, thanks a lot for the update. Can you add a reference to the kernel update that fixed the issue? It may be helpful for the future...

Best, Attilio

**Comment by larry77** [comment]
Good point. All I know is here

    ~$ cat /proc/version
     Linux version 4.9.0-3-amd64 (debian-kernel@lists.debian.org) (gcc version 6.3.0 20170516 (Debian 6.3.0-18) ) #1 SMP Debian 4.9.30-2+deb9u2 (2017-06-26)

As you can see the kernel was patched very recently.
