### ISSUE TITLE
New World Bank provider

### ISSUE THREAD

**Issue by amattioc** [amattioc/SDMX#141]
The new provider is SDMX 2.1 compliant

Endpoint: http://api.worldbank.org/v2/sdmx/rest

**Comment by charphi** [comment]
This new provider has also an https endpoint.
Could you change it in the code to enforce use of https ? See #102

**Comment by amattioc** [comment]
You're rigtht, I had not noticed that WB supported https. I'll switch it in next commit.

**Comment by charphi** [comment]
Thanks

**Comment by amattioc** [comment]
Done in  4ab75b2
