### ISSUE TITLE
Add FAQ section to Wiki

### ISSUE THREAD

**Issue by amattioc** [amattioc/SDMX#144]
In particular:

- proxy errors
- https errors
- ...

**Comment by eliamoracci** [comment]
How do you deal with the r(672) error "Server refused to send file"?

**Comment by amattioc** [comment]
Hi @eliamoracci did you get this code from a provider? Could you write the query? I would like to investigate...

**Comment by AGalatescu** [comment]
Hi @amattioc,
SDMX works fine when I try to retrieve data directly to Matlab.
However, when I try to add a provider that asks for username and password, I receive an error message:
HTTP error code 407 doesn't have a defined SDMX meaning
Could you please tell me how to fix this?

Thank you and best regards,
Adriana

**Comment by vpinna80** [comment]
Hellp @AGalatescu , 407 usually means that you have to configure a proxy.
Please follow the [wiki section](https://github.com/amattioc/SDMX/wiki/System-Configuration#network-settings) that explains how to do it.
