### ISSUE TITLE
INSEE connection is broken

### ISSUE THREAD

**Issue by remydavid** [amattioc/SDMX#145]
Tried to explore INSEE data using the SDMX Helper but got an error 

Contacting web service with query: https://bdm.insee.fr/series/sdmx/dataflow/all/all/latest/
 Exception. Class: javax.net.ssl.SSLHandshakeException - Message: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
 Exception. Class: it.bancaditalia.oss.sdmx.exceptions.SdmxIOException .Message: Connection problems while talking to endpoint: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

Other providers are working fine.

**Comment by pierre-lamarche** [comment]
I think I had a very similar issue one month ago. You can find some workarounds in the wiki of this repository or in other issues that have already been submitted, but basically all you need is to update your Java keychain (which probably does not contain the Insee certificate, as the path to Insee's BDM has changed recently). Try downloading the certificate manually (through your browser for instance) and updating the Java keychain (to do so, it depends on your OS I think but you can find some guidance on Internet).

**Comment by vpinna80** [comment]
Hi remy, this is not a problem with the SDMX tools, but with the INSEE provider certificate that is signed by [Certigna](https://www.certigna.fr/index.xhtml), that, in turn, is a certification authority not recognized by some Java versions.
You may either:
1. Ask your IT support to distribute the CA certificates of Certigna into your java distribution;
1. [Manually import the INSEE certificate](https://docs.oracle.com/javase/tutorial/security/toolsign/rstep2.html) into your Java "cacerts" file (you need to have admin permissions on your PC);
1. Use a [custom configuration.properties](https://github.com/amattioc/SDMX/wiki/System-Configuration) file to either:
    * turn off certificate validation path analysis (discouraged);
    * use a custom certificate trust store instead of Java's default one.

**Comment by amattioc** [comment]
In the configuration file you can even set INSEE to use http instead  of https:

`providers.INSEEE.endpoint=http://bdm.insee.fr/series/sdmx`

**Comment by amattioc** [comment]
Hi @remydavid is it working now? In that case, I would like to close the issue.

Best, Attilio

**Comment by amattioc** [comment]
Closing with no feedback.
