### ISSUE TITLE
ILO: error when getting a single time series

### ISSUE THREAD

**Issue by charphi** [amattioc/SDMX#148]
I have a 501 http error when I call a single ts with the ILO client.
The generated query is: http://www.ilo.org/ilostat/sdmx/ws/rest/data/ILO,DF_CPI_BEL_CPI_TCPI_COI_RT,1.0/CPI.BEL.A.279.CPI_TCPI_RT.COI_COMPONENT_CLO/

But the valid one is (no slash char at the end):
http://www.ilo.org/ilostat/sdmx/ws/rest/data/ILO,DF_CPI_BEL_CPI_TCPI_COI_RT,1.0/CPI.BEL.A.279.CPI_TCPI_RT.COI_COMPONENT_CLO

**Comment by charphi** [comment]
By the way, it seems that you can now list dataflows by using this query:
http://www.ilo.org/ilostat/sdmx/ws/rest/dataflow/ILO/ 

The doc is still available at:
http://www.ilo.org/ilostat/content/conn/ILOSTATContentServer/path/Contribution%20Folders/statistics/web_pages/static_pages/technical_page/ilostat_appl/SDMX_User_Guide.pdf

**Comment by amattioc** [comment]
Hi @charphi thanks for the hint. I'll upload a cumulative commit that fixes for this issue together with the PR #147 merge.

Thanks, Attilio

**Comment by amattioc** [comment]
Fixed in  4ab75b2
