### ISSUE TITLE
Using SDMX Help - Error in check query

### ISSUE THREAD

**Issue by rshatfield** [amattioc/SDMX#149]
The error is:
SEVERE: Exception. Class: it.bancaditalia.oss.sdmx.exceptions.SdmxXmlParsingException .Message: Error detected while parsing SDMX response: ParseError at [row,col]:[1,178]
Message: The element type "br" must be terminated by the matching end-tag "</br>".

Set up from SDMX help:
provider: IMF2 and data: DS-GFSCOFOG/.GB.S13.XDC._T

Also tried:

>result = getTimeSeries('IMF2', 'DS-GFSCOFOG/.GB.S13.XDC._T');
Nov 10, 2017 10:16:39 AM it.bancaditalia.oss.sdmx.client.RestSdmxClient runQuery
INFO: Contacting web service with query: http://dataservices.imf.org/REST/SDMX_XML.svc/CompactData/GFSCOFOG/.GB.S13.XDC._T?format=compact_v2
Nov 10, 2017 10:16:39 AM it.bancaditalia.oss.sdmx.client.RestSdmxClient runQuery
INFO: Contacting web service with query: http://dataservices.imf.org/REST/SDMX_XML.svc/CompactData/GFSCOFOG/.GB.S13.XDC._T?format=compact_v2
Error in .jcall("RJavaTools", "Ljava/lang/Object;", "invokeMethod", cl,  : 
  it.bancaditalia.oss.sdmx.exceptions.SdmxXmlParsingException: Error detected while parsing SDMX response: ParseError at [row,col]:[1,178]
Message: The element type "br" must be terminated by the matching end-tag "</br>".
Package details:
Packaged: 2017-03-02 15:51:33 UTC; pkgadm
Repository: CRAN
Date/Publication: 2017-03-09 18:08:34
Built: R 3.4.2; ; 2017-11-05 01:07:30 UTC; windows

**Comment by amattioc** [comment]
Hi @rshatfield I just had a try and it works for me. What version of the connectors are you using? (You can check the **build id** in the **help -> about** panel of the helper.

![immagine](https://user-images.githubusercontent.com/8512242/32654330-1710afaa-c60b-11e7-88f1-ace56aa1592e.png)

**Comment by rshatfield** [comment]
Hi, thanks for quick response:
SDMX Connectors Project. Build ID: 20170202-0957

**Comment by rshatfield** [comment]
Thankyou, download from github, as install.packages gives me 1.7...

**Comment by amattioc** [comment]
Great. I'll update the CRAN release asap.
