### ISSUE TITLE
empty result should throw error

### ISSUE THREAD

**Issue by pdgilbert** [amattioc/SDMX#15]
In the case of no series being returned I think rather than returning an empty list it may be better to throw an error, "series ___ not found" or "no data available for series ___", if those can be distinguished. e.g.

 z <- getSDMX('IMF', 'PGI.CA.BIS.FOSLB.A.L_M')
 str(z)
 Named list()
 
 length(z)
[1] 0

**Comment by amattioc** [comment]
Fixed in 3ae015534f6c8bd6076e04fbf3215327e3bb2ae4
