### ISSUE TITLE
IMF endpoint decommissioned

### ISSUE THREAD

**Issue by charphi** [amattioc/SDMX#153]
It seems that the IMF endpoint has been "decommissioned". (http://sdmxws.imf.org/SDMXRest)
IMF2 works properly and should be its successor. (http://dataservices.imf.org/REST/SDMX_XML.svc)

By the way, the dataflow id that I use for testing the service has changed so the data coverage of the new endpoint might be different.

**Comment by amattioc** [comment]
Yes, it seems that some flows of the IMF endpoint are not available in IMF2 (or their name has changed). E.g. WEO

**Comment by amattioc** [comment]
Hi @charphi, the provider has been removed in 23dc5ba7fc4cf1386bdbecdf06fcf22931db96e1
