### ISSUE TITLE
Enviroment variables require admin premissions

### ISSUE THREAD

**Issue by dur41d** [amattioc/SDMX#155]
Hi,

The fact that tool requires users to change the environment variables requires the the user to have admin access to be able to change these variables. In many work environments this is complicated and requires sending a ticket to the network administrator. 

It's will be more convenient if the tool relies on configuration values that are included in with the tool like local files for example.

Thanks

**Comment by amattioc** [comment]
Hi @dur41d thanks for the feedback. 
Are you referring in particular to the Excel connector (where you have to potentially specify 3 variables) or do you think this applies to all connectors?

Attilio

**Comment by dur41d** [comment]
Hi @amattioc sorry I didn't specify. Yes I'm referring to the Excel connector.

**Comment by amattioc** [comment]
Uhm, it's not easy to have a simple yet reliable mechanism for this. 

I was thinking we could reserve a couple o cells for these parameters, but this solution would require you to set the cells of every sheet that you use.

As an alternative we could default to a well known windows directory (e.g %userprofile%) for placing the jar and the property file.

**Comment by dur41d** [comment]
I agree it's tricky. Maybe one of the options is designate a sheet named for example 'SDMX_Settings' with designated cells for the settings. Another option is to look for the current directory for the excel workbook. 

These options don't have to be mutually exclusive, for example the add-on could look for the 'SDMX_Settings' sheet first and then the current directory and then fall back to the environment settings just to give the user extra options.

**Comment by amattioc** [comment]
Hi I think it makes sense... we'll do it this way

**Comment by amattioc** [comment]
Hi @dur41d 

in commit 705fcef I just added the possibility to set the main configuration aspects by means of a sheet called **SDMX SETTINGS**.

![immagine](https://user-images.githubusercontent.com/8512242/39627893-93c56bf0-4fa7-11e8-8185-79c5c90b1292.png)

If any of the parameters is not found, the macro will follow the usual steps...

Please let me know if this is in line with what we discussed...

Best, Attilio

**Comment by dur41d** [comment]
I think that will work for us. Many thanks for implementing this feature @amattioc

**Comment by amattioc** [comment]
Great. I dropped the current directory option because, if the code is put in an add-in or similar, the concept of current directory could be misleading.
