### ISSUE TITLE
Configuring a local provider

### ISSUE THREAD

**Issue by ghawkins-ott** [amattioc/SDMX#158]
I am trying to configure a local provider and I'm afraid I don't understand the syntax.  I've downloaded some SDMX files from a provider's website (two files, data and structure) but am not sure how to add them.  So far, i've put the two files in their own folder and added it like this:

addLocalProvider('data', '/path/156/', 'somedata')

But, I'm unfortunately not sure what to do next.  I'd like to convert the entire file to a dataframe (and upload it to a database).

**Comment by vpinna80** [comment]
Hi ghawkins-ott,
to be able to use `addLocalProvider`, you must place the files you downloaded in a folder structure that resembles the SDMX 2.1 specification. Also, perhaps just two or three files won't suffice, you need at least the Dataflows and DSD files other than the data itself.

**Comment by ghawkins-ott** [comment]
Appreciate the help.. I'm too stupid / new to figure it out though ;).  The files i'm using come in a .ZIP format and extract two different SDMX files (Generic -- with data, and Structure -- with code lists).  So maybe I'm not getting enough files from the provider to use this package?

**Comment by vpinna80** [comment]
The problem is that with only two files (one structure and one data file) you will be able to perform only ONE query on that provider (the query with all series in it). In other words, you won't be able to drill down your query to single time series. The local provider implementation was not meant to act as a SDMX server, but as a mirror for an existing provider, where you synchronize data by crawling the server with an external tool and storing results in your file system.

Perhaps, if the SDMX source from which you're trying to extract data is publicly accessible, we may be able to come up with a different solution.

**Comment by ghawkins-ott** [comment]
Much appreciate your assistance.  Here's an example of a file I'm looking to load: http://www12.statcan.gc.ca/datasets/Alternative.cfm?PID=103267&EXT=SDMX

I'm actually not that interested in drilling down to a single time series, but want to take the entire file, apply the code tables, and move it to a dataframe so I can load it into a postgresql database.  I've tried doing it in R but some of the SDMX files that Statistics Canada uses are too large and can't be loaded into R.

**Comment by vpinna80** [comment]
Unfortunately, the files at the attached link, provided by Statistics Canada, don't define dataflows. As such, at the moment there's no available method to parse those files, as SDMX connectors current implementation requires a dataflow structure defitinion to work.

As an alternative, you may use XSLT to transform those files into CSVs, or even split them with with a simple batch script matching codelist elements.

**Comment by amattioc** [comment]
Hi @ghawkins-ott 

the local provider feature has been thought as a simulation of an online provider based on local files and for this reason it needs the chain dataflow-dsd-data to exist in the files.

Anyway, let me think if we can tweak it a little for making it work with dsd and data only... I'll keep you posted.

Best, Attilio

**Comment by ghawkins-ott** [comment]
@amattioc Thanks!  

@vpinna80 In the meantime, could you provide any more detail on using XSLT?  I am not sure how to use the "Structure" file as a stylesheet...

**Comment by vpinna80** [comment]
Try [this snippet](https://gist.github.com/vpinna80/79d2afb2033d6f79e169ae8065cb77d2), it will extract each series' codes as a (sort of a) CSV.
Unfortunately I cannot point to specific tools for transformation in R.

Here's some sample output:
```
GEO=01,A11_Area_Residence=1,AGEGR5=1,Sex=1,MTgResps=1,MTgCount=1
GEO=01,A11_Area_Residence=1,AGEGR5=1,Sex=1,MTgResps=1,MTgCount=2
GEO=01,A11_Area_Residence=1,AGEGR5=1,Sex=1,MTgResps=1,MTgCount=3
GEO=01,A11_Area_Residence=1,AGEGR5=1,Sex=1,MTgResps=2,MTgCount=1
GEO=01,A11_Area_Residence=1,AGEGR5=1,Sex=1,MTgResps=2,MTgCount=2
GEO=01,A11_Area_Residence=1,AGEGR5=1,Sex=1,MTgResps=2,MTgCount=3
GEO=01,A11_Area_Residence=1,AGEGR5=1,Sex=1,MTgResps=3,MTgCount=1
GEO=01,A11_Area_Residence=1,AGEGR5=1,Sex=1,MTgResps=3,MTgCount=2
GEO=01,A11_Area_Residence=1,AGEGR5=1,Sex=1,MTgResps=3,MTgCount=3
GEO=01,A11_Area_Residence=1,AGEGR5=1,Sex=1,MTgResps=4,MTgCount=1
GEO=01,A11_Area_Residence=1,AGEGR5=1,Sex=1,MTgResps=4,MTgCount=2
GEO=01,A11_Area_Residence=1,AGEGR5=1,Sex=1,MTgResps=4,MTgCount=3
GEO=01,A11_Area_Residence=1,AGEGR5=1,Sex=1,MTgResps=5,MTgCount=1
GEO=01,A11_Area_Residence=1,AGEGR5=1,Sex=1,MTgResps=5,MTgCount=2
```
