### ISSUE TITLE
Upgrade to Java 8

### ISSUE THREAD

**Issue by charphi** [amattioc/SDMX#161]
Upgrading to Java 8 will bring this improvements:

- New language features (lambda expressions, virtual extension methods, ...)
- New APIs (Date and Time, ...)
- Improved security
- Java 7 is no more publicly supported since April 2015
- Available on all platforms

[Java SE 8 Features and Enhancements](http://www.oracle.com/technetwork/java/javase/8-whats-new-2157071.html)

**Comment by vpinna80** [comment]
Hi charpi, unfortunately we've upgraded our production environment to Java 7 just now, so we'll have to be relying on in for the next future.
We'll be eager to upgrade to Java 8 when it will become possible.
Keep in mind that you can always use Java 8 runtime to run the SDMX connectors.

**Comment by vpinna80** [comment]
CURRENT STATUS as of 08/02/2021:
An upgrade to our production environment was finally scheduled to be completed in a few months.
At that point we're migrating all our builds Java 8.
Most of the software is already Java 8 compliant so hopefully that wouldn't take a lot of time.

**Comment by amattioc** [comment]
fixed in b0b80be0e9f758087c7ccdfb8f065755dcb1b558
