### ISSUE TITLE
Problem with provider ECB

### ISSUE THREAD

**Issue by Jo-Fleck** [amattioc/SDMX#169]
This issue seems related to #106 which @Samuel-P-R appears to have mastered.

I am using the getdata package in Stata. (My apologies for asking about this package here - I was not able to get help from its documentation.)

I've written code for a group of users. While the query "getdata ts ECB, rest(ICP.M.ES.Y.000000.3.INX)" works perfectly on some machines, a few users report the following error:
_ERROR: No data matched the query specified. Please check the query by running: getdatacodes_

I've noticed that it does not depend on the os (windows/mac), the Stata version (15.0/15.1) but seems to be related to the query and the provider: 

When I query the series using getdatacodes on those machines on which it works the query is 
http://**sdw-ecb-wsrest.ecb.de**/service/data/ECB,ICP,1.0/M.ES.Y.000000.3.INX?detail=serieskeysonly

But on those machines where it fails it is
http://**sdw-wsrest.ecb.europa.eu**/service/data/ECB,ICP,1.0/M.ES.Y.000000.3.INX?detail=serieskeysonly
This difference seems to lead to a connection error because the second query is followed by:
_Connection failed. HTTP error code : 503, message: Service Temporarily Unavailable_

My questions:
1) Is this the reason why it works on some machines and not on others?
2) What's causing the different queries? (How can I fix it?)

Thanks a lot for any advice - and grazie mille to @amattioc for this great tool!

**Comment by vpinna80** [comment]
The `getdata` package is not part of this project, so we wouldn't be able to help you with that.
If instead you use our implementation of the connectors, you can get help from the [**SDMX Connectors for Stata Wiki**](https://github.com/amattioc/SDMX/wiki/SDMX-Connector-for-STATA).
Just as an example, your query would be written as `getTimeSeries ECB ICP/M.ES.Y.000000.3.INX`.
As for the connection problems, every once in a while some providers are overloaded or in maintenance, so the best thing to do is wait and try again later.
Let us know if you have more issues.

**Comment by Jo-Fleck** [comment]
Thanks for your prompt reply @vpinna80 !

I have now adjusted the code so it uses your implementation (added the release files to Stata's adopath) and I removed the getdata package entirely.

However, when I run the code you posted, this is what I get:

. getTimeSeries ECB ICP/M.ES.Y.000000.3.INX
< is not a valid command name
(error occurred while loading getTimeSeries.ado)
r(199);

I've checked multiple times to make sure getTimeSeries.do is in the adopath and it is. In fact, when I type -sdmxHelp- the Helper window opens up as expected and -addProvider- has the expected behavior.

Do you have any advice how to fix this problem?

**Comment by amattioc** [comment]
Maybe the adopath is messed up after uninstalling getdata?

**Comment by vpinna80** [comment]
Make sure you delete **`getTimeSeries.do`** - the correct file name is **`getTimeSeries.ado`**.
It may be an old version left by getdata package.

**Comment by Jo-Fleck** [comment]
Thanks to both of you for your replies!

I downloaded your latest Stata release, saved it in a separate folder and I added the directory with adopath + "dir_with_release" so no file from the getdata package is used any longer.

After doing this, I was able to solve one problem while another remains:

1) Querying the ICP time series does not work because the series key was incorrect; I consulted the ECB's GES Database Guide and found that the correct institution is either Eurostat or national statistical institutes (3 in the key has to be 4 or 1). So this problem was caused by the legacy code I was trying to update and is not related to the SDMX connector.

2) On the machines of some colleagues, getTimeSeries produces this error for any series key:

METADATA is disabled.
Exception. Class: it.bancaditalia.oss.sdmx.util.SdmxException .Message: Exception. Class: it.bancaditalia.oss.sdmx.util.SdmxException .Message: Exception. Class: java.net.UnknownHostException .Message: sdw-wsrest.ecb.europa.eu
r(-1);

end of do-file

r(-1);

This is independent of the Stata version and operating system. However, I noticed it works on desktop machines but not on laptops. So I guess it has to do with the network settings (proxy) or the provider settings...

Do you think this is a correct guess? If no what else might be going wrong?

Thanks a lot for your help and suggestions - have a nice weekend!

**Comment by Jo-Fleck** [comment]
One more detail related to my guess: When I open the SDMX Helper tool on a machine on which getTimeSeries works and query a specific series, the following lines appear in the lower panel:

ENTRY
RETURN
ENTRY
Contacting web service with query: http://sdw-ecb-wsrest.ecb.de/service/data/ECB,ICP,1.0/M.AT.Y.000000.3.INX?detail=serieskeysonly
ENTRY
Getting proxy for host: sdw-ecb-wsrest.ecb.de
proxy: [DIRECT]
RETURN
ENTRY
Getting proxy for host: sdw-ecb-wsrest.ecb.de
proxy: [DIRECT]
RETURN
Connection opened. Code: 200
ENTRY
...

**Comment by amattioc** [comment]
Hi, yes I think your guess is correct: that message is typical of when you have to set a proxy.

You should try and understand why the network settings are different between PC and laptop, maybe ask your IT support.

Anyway, to configure a proxy, you can use the settings described here: https://github.com/amattioc/SDMX/wiki/System-Configuration#network-settings

**Comment by Jo-Fleck** [comment]
Thanks a lot for this information! 

I'll try to figure out what the difference is exactly and how to configure the proxy.

**Comment by Jo-Fleck** [comment]
Quick follow up: As I was working through the System Configuration info, I noticed a broken link:
[https://github.com/amattioc/SDMX/wiki/System-Configuration#configuration-file-behaviour](url)

**Comment by amattioc** [comment]
I restored the [configuration example](https://github.com/amattioc/SDMX/blob/master/JAVA/configuration.properties)

**Comment by Jo-Fleck** [comment]
Thanks for restoring the link!

I am still waiting for an informative answer from our IT department regarding the laptop problem...

In the meantime, I have been able to narrow the problem down further: I was suspecting the Stata internet settings (proxy server, authentication) might be different between laptops and desktops. But they are identical so the problem must be related to some specific internet access setting on the laptops.

**Comment by amattioc** [comment]
Hi @Jo-Fleck any updates on the issue?

**Comment by Jo-Fleck** [comment]
Hi! I am still waiting to hear from our IT department... I followed up with them but was told not to expect an answer before tomorrow.

In any event, it seems this is a rather idiosyncratic problem which probably affects few users so maybe it's better to close the issue.

**Comment by amattioc** [comment]
Hi, I'll close it for now, but if you find out that the connector is part of the problem or if you need further info, please feel free to reopen,

Best, Attilio
