### ISSUE TITLE
Misconfiguration if used as library

### ISSUE THREAD

**Issue by charphi** [amattioc/SDMX#171]
When sdmx connectors is used as a library in another application, it disrupts the system config.

For example, if I call `new EUROSTAT()`, at least two things append:
1. a console handler is created at `Configuration:130` (I don't want this in my peculiar use case)
2. the system property `http.agent` is set to `SDMX` at `Configuration:209`

A possible solution would be to call `Configuration#init()` explicitly at application startup instead of static constructor.

**Comment by amattioc** [comment]
Hi @charphi, I agree it's time for a refactoring of the configuration management of the connectors... 

I'll keep this issue to track this activity

**Comment by amattioc** [comment]
Hi @charphi, I just pushed commit 71c328d98bf1d88ca40dd4015c1074015475a223 that should address your suggestions. Can you check?

Best, Attilio

**Comment by charphi** [comment]
I will test it as soon as possible
