### ISSUE TITLE
issue with Connector for STATA

### ISSUE THREAD

**Issue by cba58** [amattioc/SDMX#172]
Hi, yesterday I was using the connector for STATA and all of a sudden I started receiving the following message when trying to retrieve the data (or even connecting to the dataset with sdmxHelp):

. Flows for OECD not cached. Calling Provider.
ENTRY
Client for OECD does not exist. I will create it.
ENTRY
Create an SDMX client for 'OECD'
RETURN
RETURN
ENTRY
Contacting web service with query: https://stats.oecd.org/restsdmx/sdmx.ashx/GetDataStructure/ALL
Using proxy: HTTP @ xxxxxxx

I have this problem with other providers, IMF, WB, etc.. For instance, with IMF:
Flows for IMF_SDMX_CENTRAL not cached. Calling Provider.
ENTRY
RETURN
ENTRY
Contacting web service with query: https://sdmxcentral.imf.org/ws/public/sdmxapi/rest/dataflow/all/all/latest/
Using proxy: DIRECT
Exception. Class: java.net.UnknownHostException - Message: sdmxcentral.imf.org
Exception: 
Exception. Class: it.bancaditalia.oss.sdmx.exceptions.SdmxIOException .Message: Connection problems while talking to endpoint: sdmx central.imf.org

Is it a temporary issue with the server?

Thank you.

**Comment by amattioc** [comment]
Hi @cba58 ,
from the traces I cannot understand if you have configured a proxy or not: 
I see 

`Using proxy: HTTP @ xxxxxxx` that makes me think you configured a proxy, but then:

`Using proxy: DIRECT` that means that no proxy is configured....

Can you give us details?

All the best.

**Comment by cba58** [comment]
Hi @amattioc ,
yes, I have configured a proxy.
Best

**Comment by amattioc** [comment]
Ok, so it seems that when you get the 
`Exception. Class: java.net.UnknownHostException - Message: sdmxcentral.imf.org` 
the proxy is not being used, because I see that the connection is direct: 
`Using proxy: DIRECT`

What's the error that you get when querying the OECD provider?

**Comment by cba58** [comment]
Besides the example already provided above, a query through Stata gives the following message:

. getTimeSeries OECD NAAG/DNK+NZL+CHE+CHL+CHN.P7S+P6S+P3S13S+P51S+TOT
METADATA is disabled.
Dataflow NAAG not cached. Calling Provider.
ENTRY
RETURN
ENTRY
Contacting web service with query: https://stats.oecd.org/restsdmx/sdmx.ashx/GetDataStructure/NAAG
Using proxy: HTTP @ xxxx
Exception. Class: java.lang.NullPointerException .Message: null

r(-1);

**Comment by cba58** [comment]
1. version 2.1.2
2. I don't know how to do it
3. that works

**Comment by amattioc** [comment]
Uhm 2.1.2 has not been finalized yet. Could you move to the latest public release 2.1.0? https://github.com/amattioc/SDMX/releases/tag/v2.1.0

Let me know if anything changes

**Comment by cba58** [comment]
sorry for the misunderstanding, but I am actually using release 2.1.0 (I downloaded it a month ago)

**Comment by amattioc** [comment]
Ok.
To increase the trace level override the configuration file trace settings with these lines:

`SDMX.level = FINEST`
`handlers=java.util.logging.ConsoleHandler`
`java.util.logging.ConsoleHandler.level = FINEST`
`java.util.logging.ConsoleHandler.formatter = java.util.logging.SimpleFormatter`

I hope we'll be able to get a clue from the output

**Comment by cba58** [comment]
I am afraid I do not find the configuration file for Stata. The Wiki does not help to understand how to get there.

**Comment by vpinna80** [comment]
Hi @cba58, how did you configure your proxy?
If you didn't configure it explicitly, the connectors wouldn't use it.
So somewhere in your system there must be a configuration file. 
Usually, the file is located in the directory where you launched Stata from.
So first you need to locate your configuration file, then run the following command at the Stata prompt:
`. pwd`
and then copy your configuration file to that location.
After that, try your query again.

**Comment by cba58** [comment]
After creating configuration files in different folders (...) and including your text, I get this message now when connecting via sdmxHelp:

`
. Flows for OECD not cached. Calling Provider.
ENTRY
Client for OECD does not exist. I will create it.
ENTRY
Create an SDMX client for 'OECD'
RETURN
RETURN
ENTRY
Contacting web service with query: https://stats.oecd.org/restsdmx/sdmx.ashx/GetDataStructure/ALL
Using proxy: DIRECT
Exception. Class: java.net.UnknownHostException - Message: stats.oecd.org
Exception: 
Exception. Class: it.bancaditalia.oss.sdmx.exceptions.SdmxIOException .Message: Connection problems while talking to endpoint: stats.oecd.org
`

**Comment by cba58** [comment]
Ok, thank you. In the meantime I tried to query with MATLAB and I get:

Sep 04, 2018 6:14:37 PM it.bancaditalia.oss.sdmx.util.Configuration init

INFO: Central configuration file found: C:\Program Files\MATLAB\R2017a\toolbox\MatSDMX\configuration.properties

Sep 04, 2018 6:14:37 PM it.bancaditalia.oss.sdmx.client.RestSdmxClient runQuery

INFO: Contacting web service with query: https://stats.oecd.org/restsdmx/sdmx.ashx/GetDataStructure/NAAG

Sep 04, 2018 6:14:38 PM it.bancaditalia.oss.sdmx.client.RestSdmxClient runQuery

INFO: Contacting web service with query: https://stats.oecd.org/restsdmx/sdmx.ashx/GetDataStructure/NAAG

Sep 04, 2018 6:14:38 PM it.bancaditalia.oss.sdmx.client.RestSdmxClient runQuery

INFO: Contacting web service with query: https://stats.oecd.org/restsdmx/sdmx.ashx/GetData/NAAG/DNK%2BNZL.P7S%2BP6S%2BP3S13S%2BP51S?format=compact_v2

Error using datenum (line 181)
DATENUM failed.

Error in timeseries/init (line 299)
               [~, data, quality, I] = timeseries.utsorttime(datenum(time),...

Error in timeseries (line 324)
                  this = init(this,varargin{:});

Error in convert>convertSeries (line 85)
            ts = timeseries(arrayObservations, arrayTimeSlots);

Error in convert (line 43)
		ts = convertSeries(series);

Error in getTimeSeries (line 73)
	list = convert(result);

Caused by:
    Error using datevec (line 276)
    Cannot parse date 1970.

**Comment by amattioc** [comment]
Ok, thanks. For MATLAB it seems that you are using this configuration file:

`C:\Program Files\MATLAB\R2017a\toolbox\MatSDMX\configuration.properties`

Can you show me the contents (after masking sensitive data)?

Do ECB queries work fine in MATLAB too?

**Comment by cba58** [comment]
it is very long, so I attach a file. 
[New Text Document (2).txt](https://github.com/amattioc/SDMX/files/2349535/New.Text.Document.2.txt)

I executed 
result = getTimeSeries('OECD', 'MSTI_PUB/G_XGDP.DNK')

ECB queries seem to work.

**Comment by amattioc** [comment]
Hi, in **MATLAB** I confirm that the problem is in the missing frequency for the dataflow. This makes it impossible for us to process the date format. You can use the **getTimeSeriesTable** function to get the data in this case:

`result = getTimeSeriesTable('OECD', 'MSTI_PUB/G_XGDP.DNK')`

Regarding **STATA**, in the first lines after your first call to the connector you should see something like:

`INFO: Central configuration file found: bla/bla/configuration.properties`

exactly as you see in MATLAB. Can you check if this is true?

**Comment by amattioc** [comment]
I'm pretty sure that for STATA the configuration file has lost the proxy entry for some reason. This is confirmed by the trace:

`Using proxy: DIRECT`

that should be like in MATLAB:

`Using proxy: HTTP @ xxxx`

We have to find out where the configuration file for STATA has been put. 

The MATLAB you are using is in the same pc where STATA is? Can you check if there is an environment variable named **SDMX_CONF**?

**Comment by cba58** [comment]
Yes there is and SDMX_CONF refers to the configuration file in the MATLAB folder. I still do not find the configuration file in the Stata folder.

**Comment by amattioc** [comment]
If the SDMX_CONF is present it means that even STATA should be reading it, unless another file named **configuration.properties** is present in the STATA "current directory" or unless STATA drops the environment variable before starting (very unlikey). 
I'm sure another configuration file is being read by STATA, otherwise the traces at FINE level (e.g. ENTRY, RETURN) could not be explained.

Can you run a disk search for file name "configuration.properties"?

**Comment by amattioc** [comment]
Hi @cba58, any news on this issue?

**Comment by amattioc** [comment]
Hi @cba58 I'm closing this issue as I got no response. If you need further help, please feel free to re-open it.
