### ISSUE TITLE
R Interface to SDMX Web Services - SdmxResponseException: (503)

### ISSUE THREAD

**Issue by Tenx1** [amattioc/SDMX#173]
Hello all.  I seem to be having a problem retrieving some data using the R interface RJSDMX.  

Using the function "getTimeSeries('ECB', 'BP6.M.N. * . * . * . * . T . * . FA . P . * . * . * . * . * . *')" produces the message:
 
"Error in .jcall("RJavaTools", "Ljava/lang/Object;", "invokeMethod", cl, :
it.bancaditalia.oss.sdmx.exceptions.SdmxResponseException: (503): Service temporarily unavailable. Please try again later."

I am able to use the same function successfully when applying less wildcards, i.e. as "getTimeSeries('ECB', 'BP6.*.*.BE.W1.S1.S1.T.A.FA.P.F._Z.EUR._T.M.N)".  Is there any way around this?

Thank you.

**Comment by vpinna80** [comment]
Hi @Tenx1,
Lately, the ECB seems to have placed some limits on queries that one can perform.
At the moment, we don't know exactly which policies are being enforced.
Unfortunately, there's no workaround other than splitting your query into multiple parts.

**Comment by Tenx1** [comment]
Thank you for speedy reply @vpinna80

**Comment by amattioc** [comment]
Hi @Tenx1 do you need further help with this issue?

**Comment by amattioc** [comment]
Hi @Tenx1, 

I spent some time to play a bit with the query that you wish to run and I found that if you remove the wildcard from the last dimension and you replace it with an explicit OR operator (i.e. '+') for the three available codes it works:

`result=getTimeSeries('ECB', 'BP6.M.N.....T..FA.P......C+L+N')`
`nov 02, 2018 2:27:50 PM it.bancaditalia.oss.sdmx.client.RestSdmxClient runQuery
INFORMAZIONI: Contacting web service with query: https://sdw-wsrest.ecb.europa.eu/service/dataflow/all/BP6/latest/`
`nov 02, 2018 2:27:50 PM it.bancaditalia.oss.sdmx.client.RestSdmxClient runQuery
INFORMAZIONI: Contacting web service with query: https://sdw-wsrest.ecb.europa.eu/service/datastructure/IMF/BOP/1.5/?references=children`
`nov 02, 2018 2:27:51 PM it.bancaditalia.oss.sdmx.client.RestSdmxClient runQuery
INFORMAZIONI: Contacting web service with query: https://sdw-wsrest.ecb.europa.eu/service/data/IMF%2CBP6%2C1.0/M.N.....T..FA.P......C%2BL%2BN/`

`length(result)`
`[1] 673`

The result should be exactly the same of the query that you are trying to execute, but for some reason this alternative form does not trigger the error in the server.

Please let me know if it works for you too...

Best, Attilio

**Comment by Tenx1** [comment]
Good afternoon Attilio,

Thank you for revisiting this query.  I have tested the revised syntax this
end and it functions perfectly.

Many thanks,

**Comment by amattioc** [comment]
You are welcome.
