### ISSUE TITLE
Problems accessing INSEE Data behind proxy

### ISSUE THREAD

**Issue by TcaManager** [amattioc/SDMX#174]
Hi, when trying to access this URL (INSEE) with the SDMX Helper 
[INSEE](https://bdm.insee.fr/series/sdmx/dataflow/all/all/latest/)
I get the following error code
`
sept. 19, 2018 11:10:07 AM it.bancaditalia.oss.sdmx.client.RestSdmxClient runQuery
INFOS: Contacting web service with query: https://bdm.insee.fr/series/sdmx/dataflow/all/all/latest/
sept. 19, 2018 11:10:10 AM it.bancaditalia.oss.sdmx.client.RestSdmxClient runQuery
GRAVE: Exception. Class: java.net.UnknownHostException - Message: bdm.insee.fr
sept. 19, 2018 11:10:10 AM it.bancaditalia.oss.sdmx.helper.SDMXHelper$17 run
GRAVE: Exception. Class: it.bancaditalia.oss.sdmx.exceptions.SdmxIOException .Message: Connection problems while talking to endpoint: bdm.insee.fr
`

Hi, We're working with a HTTP proxy, which exists as environment var HTTP_PROXY.

**Comment by amattioc** [comment]
Hi @TcaManager,

You should use the configuration file to add proxy settings: https://github.com/amattioc/SDMX/wiki/System-Configuration#network-settings

**Comment by amattioc** [comment]
Hi @TcaManager did the suggestion help? You can find a template for the configuration file here: https://github.com/amattioc/SDMX/blob/master/JAVA/configuration.properties

**Comment by TcaManager** [comment]
Hi, I'm on vacation si I will tell you next Monday. Thanks a lot anyway. Have a nice day.

**Comment by amattioc** [comment]
Hi @TcaManager is this issue solved? Can I close?

**Comment by amattioc** [comment]
Hi @TcaManager, if you need more help, please feel free to reopen.
