### ISSUE TITLE
Convert Excel to SDMX-ML 2.1 XML with custom DSD

### ISSUE THREAD

**Issue by KoiosW** [amattioc/SDMX#175]
Is is possible to convert Execel data to sdmx-ml 2.1 xml with personal DSD file?
If yes, how can I make it work? Thanks

**Comment by vpinna80** [comment]
Hi @KoiosW ,
at the moment the conversion would not be possible. 
It might be a part of future development.
However, if you can convert your data to SDMX 2.1 format, and provide your DSD complete with all codes, you can supply those files to our FILE provider that would allow you to query your data using our connectors.
To get started with conversion, i would souggest you to first convert it to a CSV, and then use XML style sheets to transform your CSV into the SDMX xml format.
Hope this helps.

**Comment by brainwasher** [comment]
> Is is possible to convert Execel data to sdmx-ml 2.1 xml with personal DSD file?
> If yes, how can I make it work? Thanks

Hi @KoiosW ,

the Eurostat SDMX Converter can do Excel to SDMX-ML. You can use it with a local UI, a web UI, a web service or just take the source code and build it into your own application. You can find it here: https://ec.europa.eu/eurostat/web/sdmx-infospace/sdmx-it-tools/sdmx-converter

In case you need examples how the parameters for linking the Excel workbook to a DSD works, you can look at the National Accounts templates published by Eurostat here: https://sdmx.org/?page_id=1498

Regards,
Daniel.

**Comment by amattioc** [comment]
Hi @KoiosW 

I close this issue as it is out of scope for the connectors. If you need info/help with the excel connector feel free to reopen.
