### ISSUE TITLE
ECB, IMF2 issue "/"

### ISSUE THREAD

**Issue by plegula** [amattioc/SDMX#176]
Hi

Sdmx21Queries builds query with "/" (at the end) this produces  HTTP status code: 503 on ECB servers

ok - https://sdw-wsrest.ecb.europa.eu/service/data/ECB.DISS%2CMOBILE_KEY_4%2C1.0/W%2BM%2BQ%2BS%2BA....
error - https://sdw-wsrest.ecb.europa.eu/service/data/ECB.DISS%2CMOBILE_KEY_4%2C1.0/W%2BM%2BQ%2BS%2BA..../

IMF2 - privider olso produce error when "/" apears at the end of url.
Is it nesseserly to add it to query path?

**Comment by amattioc** [comment]
Hi @plegula thanks for submitting the issue. I had noticed some strange intermittent problems in the two providers but I had not tracked them back to the final '/'.

I'll investigate the issue and I'll keep you posted.

Best, Attilio

**Comment by plegula** [comment]
Hi,
try this

curl -k -o --header "Accept:application/vnd.sdmx.structurespecificdata+xml;version=2.1" "https://sdw-wsrest.ecb.europa.eu/service/data/ECB.DISS%2CMOBILE_KEY_4%2C1.0/W%2BM%2BQ%2BS%2BA....?startPeriod=2008-01-01"

and 

curl -k -o --header "Accept:application/vnd.sdmx.structurespecificdata+xml;version=2.1" "https://sdw-wsrest.ecb.europa.eu/service/data/ECB.DISS%2CMOBILE_KEY_4%2C1.0/W%2BM%2BQ%2BS%2BA..../?startPeriod=2008-01-01"

those requests differ only with "/" but may be it is connected with different "things". 
Thanks

**Comment by amattioc** [comment]
Hi @plegula, I just pushed commit 2ffba3c8bcd4ff4a9dca356e7993d8b1ae69e8dd to fix this issue.

I removed the final '/' that was creating problems, but I had to introduce a custom provider for WB and INEGI, because they apparently needed it.

Please let me know if this solves your problem...

Best, Attilio

**Comment by plegula** [comment]
Yes, it solved my problem.

Thanks
