### ISSUE TITLE
SDMS-2.1.2 connection problem to INSEE

### ISSUE THREAD

**Issue by AllOtherUsernamesWereAlreadyTaken** [amattioc/SDMX#179]
Hi,

I downloaded the sdmx.jar file from https://jar-download.com/artifact-search/sdmx because i couldn't find it anywhere else.
Double clicked it. Seems to work for all Providers, except INSEE, the only one I'm interested in.
`déc. 06, 2019 12:05:15 PM it.bancaditalia.oss.sdmx.client.RestSdmxClient runQuery
GRAVE: Exception. Class: javax.net.ssl.SSLHandshakeException - Message: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
déc. 06, 2019 12:05:15 PM it.bancaditalia.oss.sdmx.helper.SDMXHelper$17 run
GRAVE: Exception. Class: it.bancaditalia.oss.sdmx.exceptions.SdmxIOException .Message: Connection problems while talking to endpoint: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
`

**Comment by vpinna80** [comment]
Hi, you should install the INSEE server certificate into your Java cacerts file.
You can download the certificate by connecting with your browser to the following address:
https://bdm.insee.fr/series/sdmx/dataflow/all/all/latest
The certificate download option is usually on the left of the address bar.

**Comment by AllOtherUsernamesWereAlreadyTaken** [comment]
Java isn't installed on my computer (needed only to run the "helper"). I found an easier way to get the info out of the INSEE website, using a PowerQuery straight from Excel. Thx for your help and dedication.

**Comment by amattioc** [comment]
thanks
