### ISSUE TITLE
OECD connection failed

### ISSUE THREAD

**Issue by Lord-Keynes1** [amattioc/SDMX#186]
Hey guys,

So I am using the SMDX helper tool on stata and when I click on the OECD as the provider, I get this:

 Contacting web service with query: http://stats.oecd.org/restsdmx/sdmx.ashx//GetDataStructure/ALL
 Connection failed. HTTP error code : 302, message: Redirect

 Exception. Class: it.bancaditalia.oss.sdmx.util.SdmxException .Message: Connection failed. HTTP error code : 302, message: Redirect

ECB seems to be working, and so is Eurostat, but not the IMF. Has anyone come across this? I'm not using a VPN nor am I using a proxy. Thanks

**Comment by amattioc** [comment]
Hi, both OECD and IMF2 are working with my RJSDMX v2.3.3. What version are you using?

**Comment by amattioc** [comment]
Hi again, another question: are you using the **getdata** tool?

**Comment by Lord-Keynes1** [comment]
I am using the **getdata** tool for Stata. Let me see if I can find the version used by the getdata tool.

**Comment by Lord-Keynes1** [comment]
I think it is using version 2.1. I updated the getdata tool but it stays at 2.1. Maybe it hasn't been updated since 2.1

**Comment by Lord-Keynes1** [comment]
I downloaded the latest sdmx version for STATA from here and replaced it in the file where the old version is. I still get the same error.

**Comment by amattioc** [comment]
Make sure to replace the jar. This is the latest: https://github.com/amattioc/SDMX/releases/download/v2.3.3/SDMX.jar

**Comment by Lord-Keynes1** [comment]
I replaced it with the version with that version. Now I get the following error:

java.lang.ClassNotFoundException: it.bancaditalia.oss.sdmx.client.StataClientHandler
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at com.stata.Javacall.load(Javacall.java:119)
        at com.stata.Javacall.load(Javacall.java:90)

I went to the ado file which has the datacodes command, and it is basically this:
``
cap program drop getdatacodes
program getdatacodes
version 13
javacall it.bancaditalia.oss.sdmx.client.StataClientHandler sdmxHelper
end
``

The file I replaced is still called sdmx and it is still in the same place, so there shouldnt be any problem, from what I understand. This is just a subroutine to call the sdmx.jar using Java. Any ideas?

**Comment by amattioc** [comment]
Can you try this one? 
https://github.com/amattioc/SDMX/blob/master/STATA/jar/SDMX.jar

**Comment by aaron72** [comment]
May 18, 2020 11:30:51 AM it.bancaditalia.oss.sdmx.client.RestSdmxClient runQuery
INFO: Contacting web service with query: https://sdw-wsrest.ecb.europa.eu/service/dataflow/all/all/latest
May 18, 2020 11:32:52 AM it.bancaditalia.oss.sdmx.client.RestSdmxClient runQuery
SEVERE: Exception. Class: java.net.SocketException - Message: Operation not permitted (connect failed)
May 18, 2020 11:32:52 AM it.bancaditalia.oss.sdmx.helper.SDMXHelper$17 run
SEVERE: Exception. Class: it.bancaditalia.oss.sdmx.exceptions.SdmxIOException .Message: Connection problems while talking to endpoint: Operation not permitted (connect failed)

**Comment by Lord-Keynes1** [comment]
> 
> 
> Can you try this one?
> https://github.com/amattioc/SDMX/blob/master/STATA/jar/SDMX.jar

Replaced it and solved the problem. Thank you very much @amattioc !

**Comment by amattioc** [comment]
Great.
