### ISSUE TITLE
2.3.4 release

### ISSUE THREAD

**Issue by lmorandini** [amattioc/SDMX#187]
Could 2.3.4 be released? (That would simplify the build of my GeoTools datastore, avoiding a local clone and build.)

**Comment by amattioc** [comment]
Hi Luca, no problem. In some days we'll make it. Do you need it in CRAN too?

**Comment by lmorandini** [comment]
No need for CRAN, just Maven repo.

**Comment by lmorandini** [comment]
By the way, I am fixing the integration test cases for ABSso a few more days would be fine.

**Comment by lmorandini** [comment]
@amattioc, could you please post it to the public Maven repo?

**Comment by vpinna80** [comment]
A new maven release has just been completed.
Please allow a few hours for central mirrors to sync.
