### ISSUE TITLE
RStudio 1.4.1717 doesn't load RJSDMX

### ISSUE THREAD

**Issue by TOlejnik** [amattioc/SDMX#204]
Hello,

I've just updated to  **RStudio 1.4.1717** (Released on the 1st of June) and I am not able to work with RJSDMX package anymore. RStudio is constantly crashing and rebooting R session.
I had to downgrade my RStudio installation in order to work with RJSDMX.

Thank you in advance for checking the problem.

Kind regards,
Tomasz

**Comment by vpinna80** [comment]
Hello @TOlejnik,
We can confirm that RJSDMX works perfecly in the latest release of RStudio.

Please try to describe the steps to reproduce the problem, the more detailed the better.
Try to upload screenshots if you can.

**Comment by amattioc** [comment]
Hi @TOlejnik , any news on this? did you fix the problem?

**Comment by TOlejnik** [comment]
Good morning @amattioc ,

thank you very much for the follow up.  Unfortunately I didn’t have a time to check but will do that definitely in coming days and describe the problem more carefully.

Thank you again and will revert to you very soon.

**Comment by amattioc** [comment]
Hi @TOlejnik , if you still have problems please feel free to reopen
