### ISSUE TITLE
Adding provider

### ISSUE THREAD

**Issue by LeoStroncone** [amattioc/SDMX#217]
​​​​​Hi Attilio,
I added the new IstatData as follow:
> addProvider(name = 'IstatData', endpoint = 'https://esploradati.istat.it/SDMXWS/rest/') 
but in sdmxHelper I had:
GRAVE: null
GRAVE: Exception. Class: it.bancaditalia.oss.sdmx.exceptions.SdmxResponseException .Message: (100): No results matching the query.

Any solution? Thanks a lot!

**Comment by vpinna80** [comment]
Hi Leo,
it appears, at the moment, that the endpoint is not usable to external users (i.e. non-istat authorized).

***@***.***

** Le e-mail provenienti dalla Banca d'Italia sono trasmesse in buona fede e non comportano alcun vincolo né creano obblighi per la Banca stessa, salvo che ciò non sia espressamente previsto da un accordo scritto. Questa e-mail è confidenziale. Qualora l'avesse ricevuta per errore, La preghiamo di comunicarne via e-mail la ricezione al mittente e di distruggere il contenuto. La informiamo inoltre che l'utilizzo non autorizzato del messaggio o dei suoi allegati potrebbe costituire reato. La Banca d’Italia tratta i dati personali in linea con il Regolamento Europeo 2016/679 (GDPR). Per informazioni può consultarsi “Privacy” sul sito della Banca d’Italia. Per ulteriori richieste è possibile rivolgersi al Titolare del trattamento ***@***.***). E’ possibile anche contattare il Responsabile della protezione dei dati ***@***.*** **
Prima di stampare, pensa verde

** E-mail from Bank of Italy are sent in good faith but they are neither binding on the Bank nor to be understood as creating any obligation on its part except where provided for in a written agreement. This e-mail is confidential. If you have received it by mistake, please inform the sender by reply e-mail and delete it from your system. Please also note that the unauthorized disclosure or use of the message or any attachments could be an offence. The Bank of Italy processes personal data in line with Regulation (EU) 2016/679 (General Data Protection Regulation - GDPR). For any further information you can consult the Privacy Policy on the Bank of Italy webpage. In case of queries, please contact the Bank of Italy Data Controller ***@***.***) . You may also contact the Bank of Italy Data Protection Officer ***@***.*** . Thank you for your cooperation **
Think green before you print

**Comment by amattioc** [comment]
Hi @LeoStroncone , try without the final '/'

`addProvider(name = 'Istat4', endpoint = 'https://esploradati.istat.it/SDMXWS/rest')`

It works from here.

Anyway I remember that some time ago you had to explicitly request access to ISTAT, as they filtered by IP (not sure if this is still true).

**Comment by LeoStroncone** [comment]
Hi Attilio,
it's true, it works perfectly! Thanks a lot!
