### ISSUE TITLE
Add StatCan and Pacific Data Hub providers

### ISSUE THREAD

**Issue by amattioc** [amattioc/SDMX#225]
https://api.statcan.gc.ca/census-recensement/profile/sdmx/rest 

https://www12.statcan.gc.ca/wds-sdw/2021profile-profil2021-eng.cfm#key 

https://www150.statcan.gc.ca/t1/wds/sdmx/statcan/v1/rest

https://stats-nsi-stable.pacificdata.org/rest

**Comment by lucasjfriesen** [comment]
Is there anything that might assist with this?

**Comment by amattioc** [comment]
Hi @lucasjfriesen , for the StatCan API it seems that the query for ALL dataflows (or all DSDs) is not supported. 

e.g.
https://www150.statcan.gc.ca/t1/wds/sdmx/statcan/v1/rest/datastructure/all 
https://www150.statcan.gc.ca/t1/wds/sdmx/statcan/v1/rest/dataflow/all 

The Census API is ok and PacificData is fine too.

**Comment by amattioc** [comment]
Received updates form StatCan. The official endpoints are:

[https://api.statcan.gc.ca/census-recensement/profile/sdmx/rest](https://urldefense.com/v3/__https:/api.statcan.gc.ca/census-recensement/profile/sdmx/rest__;!!DKHwpfUEEKarIw!vg9XMYKgj-edwOIiXMmFKTCLPT4KLHbHUzjwfCllMiswG4I2QFlg_E1BeFMZDAAeynsFZ6UGyZ5tv4PAxQ-0ypNKMEfxt0C9QTZXuG-NL94$) (Census Profile Data)
[https://information-energie.canada.ca/sdmx/rest](https://urldefense.com/v3/__https:/information-energie.canada.ca/sdmx/rest__;!!DKHwpfUEEKarIw!vg9XMYKgj-edwOIiXMmFKTCLPT4KLHbHUzjwfCllMiswG4I2QFlg_E1BeFMZDAAeynsFZ6UGyZ5tv4PAxQ-0ypNKMEfxt0C9QTZXutVtFwU$) (Canadian Center of Energy Information)

**Comment by amattioc** [comment]
fixed 2c32212130b9e40daf2887330458cc8ee275136e
