### ISSUE TITLE
Update ECB endpoint

### ISSUE THREAD

**Issue by charphi** [amattioc/SDMX#226]
ECB is changing its endpoint:

> The SDW web services API will be repointed to the ECB Data Portal API as of the official go-live. User requests will be automatically redirected for at least a year from https://sdw-wrest.ecb.europa.eu/ to https://data-api.ecb.europa.eu/. API request syntax will remain unchanged, as data structures and codifications remain the same.

More info at https://data.ecb.europa.eu/blog/blog-posts/ecb-data-portal-live-now

**Comment by amattioc** [comment]
fixed 2c32212130b9e40daf2887330458cc8ee275136e
