### ISSUE TITLE
Build Failed: Unexpected element "{}html" {antlib:org.a pache.tools.ant}html

### ISSUE THREAD

**Issue by mrbcfc** [amattioc/SDMX#23]
This seems to be a pretty obscure issue. I've failed to resolve it through Google and following similar instances of the issue for others. But any idea why I might be getting the below error message when trying to build the Java library?

c:\E\New\MATLAB\work\SDMX>ant SDMX
Buildfile: c:\E\New\MATLAB\work\SDMX\build.xml

BUILD FAILED
c:\E\New\MATLAB\work\SDMX\build.xml:6: Unexpected element "{}html" {antlib:org.apache.tools.ant}html

Total time: 0 seconds

**Comment by amattioc** [comment]
Hi,
yes it seems a strange issue. I usually use ant from Linux (I see you are on windows) and on windows I build in eclipse. I need a couple of clarifications to help you better:

- are you pointing to the original build.xml file?
- are you running the ant command from the JAVA directory?

Cheers, Attilio

**Comment by amattioc** [comment]
Hi, 

googling around I found this bug report (related to Fedora): https://bugzilla.redhat.com/show_bug.cgi?id=838711

In that case the problem showed up even for a simple build file that just contained the single row:

</project>

Could you check if you see the same behaviour in your env?

Thanks, Attilio

**Comment by mrbcfc** [comment]
I have now installed Eclipse and tried to run your build.xml from there but still get the same error on line 6.

I also tried the simple <project/> build which actually was successful. So my ant/java installation at least works for some things which I guess puts focus back on the build file.

One user encountering this issue seemingly resolved it by clearing the CLASSPATH variable but that didn't work for me either.

Thanks again for your continued assistance.

**Comment by amattioc** [comment]
If the minimal build was successful try replacing the build.xml content with the following simplified code:

`<project name="TEST">`
`	<target name="compile" >`
`		<javac srcdir="src" destdir="."/>`
`	</target>`
`</project>`

and run it with the command:

`ant compile'

In my Win environment I use Java 6 and the only variables that are set are:

JAVA_HOME, ANT_HOME and PATH (just containing JAVA_HOME\bin and ANT_HOME\bin).

Let me know...

**Comment by mrbcfc** [comment]
Running this code was also successful. (Adding includeantruntime="false" to the javac line suppresses an error but the build runs fine either way.)

Thank you once again for your assistance.

**Comment by amattioc** [comment]
Uhm, I'm starting to think that somehow the build file you're using has something wrong that tricks the parser. It could be junk characters or it could be the comments (line six is just after a comment, but it's just a guess). 

Anyway, the following lines should compile the code and create the jar file you need. Let me know if they work:

`<project name="TEST">`
`	<target name="compile" >`
`		<mkdir dir="build"/>`
`		<javac includeantruntime="false" srcdir="src" destdir="build"/>`
`		<jar jarfile="SDMX.jar" basedir="build"/>`
`	</target>`
`</project>`

By the way, are you going to use the jar with MATLAB? In that case mind the java version you are using, since MATLAB has a 1.7 or 1.6 JVM embedded (it depends on the version) and if you compile the code with java 8 it'll not work...

Cheers, Attilio

**Comment by mrbcfc** [comment]
Thanks for that. I now have the SDMX.jar file. But how about copying the generated jar file in the dist subdir and in the correct library directories of each connector?

Good catch on the MATLAB JVM version issue - I have now downgraded to 1.6.

Thanks again.

**Comment by amattioc** [comment]
With JDK 1.6 you could try the original build file. Do you see the same issue?

**Comment by mrbcfc** [comment]
Unfortunately yes.

**Comment by amattioc** [comment]
There is definitely something in the build file. Can you please do a couple of tests?

 - test 1: copy the content of the build file from github (using the browser) in a new build.xml file and give it a run.

If nothing changes, 

- test2: remove all the comments from the build file and run again

Thanks, Attilio

**Comment by mrbcfc** [comment]
Success! test 1 worked! I'm not exactly sure why but the issue has now disappeared.

However, I am now getting undefined variable errors when trying to pull data using the various 'get' m-files. 

Example: 
Error using sdmxHelp (line 32)
SDMX sdmxHelp()() error:\nUndefined variable "it" or class "it.bancaditalia.oss.sdmx.helper.SDMXHelper.start".

I'm pretty sure I've completed all required steps for you SDMX connector. Are their other additional bits of software/clients/services/permissions/keys required to communicate with bancaditalia?

**Comment by amattioc** [comment]
OK, this means that there were junk characters somewhere in the file.

The error you see now means that the SDMX.jar is not in the MATLAB classpath. Did you modify the static classpath?

**Comment by mrbcfc** [comment]
I have a javaclasspath.txt file in my preferences folder (C:\Users\SM\AppData\Roaming\MathWorks\MATLAB\R2013a) and executing javaclasspath shows an entry for the new SDMX.jar file at the bottom of the Static Java Path list (C:\E\New\MATLAB\work\MATLAB\lib\SDMX.jar). My dynamic path is empty.

My Matlab search path contains C:\E\New\MATLAB\work and all subfolders.

I also have a startup.m file in my preferences folder with the line 'addpath C:\E\New\MATLAB\work'.

I can't personally see any issues there. Can you?

configuration.properties remains in the folder with the original build.xml file (C:\E\New\MATLAB\work\SDMX). I have a SDMX_CONF user environment variable pointing to the same folder.

**Comment by amattioc** [comment]
Yes, the configuration seems perfect.

Try if the jar file is valid by typing, from a DOS prompt:

*java -classpath SDMX.jar it.bancaditalia.oss.sdmx.helper.SDMXHelper*

**Comment by mrbcfc** [comment]
I'd actually already tried that. No good unfortunately:
C:\E\New\MATLAB\work\MATLAB\lib>java -classpath SDMX.jar it.bancaditalia.oss.sdmx.helper.SDMXHelper
Error: Could not find or load main class it.bancaditalia.oss.sdmx.helper.SDMXHelper

Many thanks once again for your continued assistance - thoroughly appreciated.

**Comment by amattioc** [comment]
OK, this means the jar file is not good. Can you unzip it and check the contents?

**Comment by mrbcfc** [comment]
I simply get:
MET-INF -> MANIFEST.MF 

Its contents are merely:
Manifest-Version: 1.0
Ant-Version: Apache Ant 1.9.4
Created-By: 1.6.0_45-b06 (Sun Microsystems Inc.)

**Comment by amattioc** [comment]
There should be a directory tree, starting with an 'it' directory and containing all the class files, just like the ones that you should see in the 'build' directory generated by the ant build.

Try repeating the build process. Do:

*ant clean*
*ant*

Then check the build dir and the jar file

**Comment by mrbcfc** [comment]
Remarkably, I hadn't noticed that the build folder was/is completely empty.

I have now performed 'ant clean' and 'ant'. My print is as below (not much). My build folder remains empty and the SDMX.jar file contents remain as before.

C:\E\New\MATLAB\work\SDMX>ant
Buildfile: C:\E\New\MATLAB\work\SDMX\build.xml

init:
    [mkdir] Created dir: C:\E\New\MATLAB\work\SDMX\build

SDMX:

dist:
    [mkdir] Created dir: C:\E\New\MATLAB\work\SDMX\dist\lib
      [jar] Building MANIFEST-only jar: C:\E\New\MATLAB\work\SDMX\dist\lib\SDMX.
jar
     [copy] Copying 1 file to C:\E\New\MATLAB\work\RJSDMX\inst\java
     [copy] Copying 1 file to C:\E\New\MATLAB\work\MATLAB\lib
     [copy] Copying 1 file to C:\E\New\MATLAB\work\SAS\lib

**Comment by amattioc** [comment]
Is the *src* folder at the same level of the build file?

**Comment by mrbcfc** [comment]
Yes. And it is also empty.

**Comment by amattioc** [comment]
It shouldn't be empty. It should contain all the java source code... :-)

**Comment by mrbcfc** [comment]
Houston, we have a dataset! src populated, libraries re-built, queries running and numbers flowing :-)

I will put the first and major issue down to gremlins but the second elementary copy/paste issue I might have to take myself!

Anyway, I guess all's well that ends well. Many thanks once again for all the help Attilio.

**Comment by amattioc** [comment]
Sure, it was a pleasure. 

Have fun with the connector, and good night... :-)
