### ISSUE TITLE
Accept header to force response in XML

### ISSUE THREAD

**Issue by LnIgrk** [amattioc/SDMX#230]
Hi @amattioc , 

I've been looking for an option to configure accept header value in the configuration file (I use STATA to query data), but I haven't found  such in here [configuration](https://github.com/amattioc/SDMX/blob/master/JAVA/configuration.properties). I've also seen this [issue](https://github.com/amattioc/SDMX/issues/126), however I am not sure what should be done on user side to force an API that use json as default to respond with XML. 

Could you please let me know if there is any way to pass accept header value as per current connector implementation ?

Thank you!

**Comment by vpinna80** [comment]
Hi @LnIgrk, 
The headers are already configured to ask each provider to return XML; if you encounter a provider which responds with JSON, please let us know so that we can look into it.

**Comment by LnIgrk** [comment]
Hi @vpinna80 ,

Thank you for your reply. 
Yes, I have added a custom provider that responds with json by default unless accept header is specified to XML. The result of requesting data or structural artefacts is a parsing error. 

![image](https://github.com/amattioc/SDMX/assets/42011153/e4a38478-80f4-4254-ba44-f6689339417a)

correct me if I am wrong, but according to this peace of code:

https://github.com/amattioc/SDMX/blob/master/JAVA/src/main/java/it/bancaditalia/oss/sdmx/client/RestSdmxClient.java

![image](https://github.com/amattioc/SDMX/assets/42011153/f539fe1a-9433-48a8-93bb-35794badaad7)

it seems that in cases when runQuery() is executed with acceptHeader == null or an empty string, it leads to
conn.setRequestProperty("Accept", "*/*") so that response format is whatever is set as a default for that specific API.

its not clear to me how can I pass the value, so that its not null or an empty string

Thank you,
Kind regards

**Comment by vpinna80** [comment]
Custom providers need their own implementing class that provides the required values for the headers when asked by the query manager; these values cannot be simply passed with configuration files.
At the moment, providers added by the user cannot have an implementing class, so you're stuck unless you change the provider implementation to return XML files by default, as compliant with SDMX 2.1 standard.

I will tag this thread as a feature request.

**Comment by amattioc** [comment]
Hi @LnIgrk does your provider implement sdmx v2.1? In this case there should be no need for a custom class

**Comment by amattioc** [comment]
Hi @LnIgrk  any news on this?

**Comment by agdavydov81** [comment]
> For metadata queries we rely in defaults.
As I see from code, the default is "\*/\*" - i.e. server can reply in any format by it own decision.
https://github.com/amattioc/SDMX/blob/5475b3e840654f0334eaf3e952ae6415cae4ca27/JAVA/src/main/java/it/bancaditalia/oss/sdmx/client/RestSdmxClient.java#L545C15-L545C15

So, the server can output in JSON, but you expecting only XML.

I will write unit test for this case.

**Comment by agdavydov81** [comment]
See the https://github.com/amattioc/SDMX/pull/236 as a very simple test.

If you place brake point at 
https://github.com/amattioc/SDMX/blob/5475b3e840654f0334eaf3e952ae6415cae4ca27/JAVA/src/main/java/it/bancaditalia/oss/sdmx/client/RestSdmxClient.java#L542C4-L542C4
you will see the issue: the default Accept header will be set to "\*/\*", not the "application/xml"

**Comment by vpinna80** [comment]
If the Accept header is set to */* for a Metadata query (like the one in your test), the server should respond with `application/vnd.sdmx.genericmetadata+xml;version=2.1`

In fact, for each type of query, the default is ALWAYS `application/vnd.sdmx.[format]+xml;version=2.1`, where [format] is the type of the query: genericdata, genericmetadata, structure, schema.

In no case the default response is expected to be a JSON document.

**Comment by msamusenka** [comment]
@vpinna80 

> If the Accept header is set to "_/_" for a Metadata query (like the one in your test), the server should respond with `application/vnd.sdmx.genericmetadata+xml;version=2.1`

Indeed, for 2.1 the default is SDMX-ML. Thanks for pointing this out. Reference: https://github.com/sdmx-twg/sdmx-rest/blob/master/doc/tips.md

**Comment by agdavydov81** [comment]
Thank you very much for explanation.
Seems I was wrong about Accept header is a mandatory type.
The only thing I have found, is SDMX _strongly recommends_ to fill the Accept header (see Tips and Tricks of cheat sheet
https://github.com/sdmx-twg/sdmx-rest/blob/v1.5.0/v2_1/ws/rest/docs/rest_cheat_sheet.pdf)

But these tips and tricks seems only recommendation.

**Comment by amattioc** [comment]
I remember that some years ago we had to review the header value because some providers behaved weirdly if it was set otherwise. I think (not sure though) that the values that are used are the once that were acceptable for all providers at that time. 

Anyway this was years ago and probably it makes sense to have a second look and a full test run. This will be done during the refactoring mentioned in issue #235

**Comment by amattioc** [comment]
fixed 2c32212130b9e40daf2887330458cc8ee275136e
