### ISSUE TITLE
Add unit tests for sdmx API v2 provider

### ISSUE THREAD

**Issue by amattioc** [amattioc/SDMX#237]
Use demo server from MT:

https://demo11.metadatatechnology.com/FusionRegistry/overview.html

Thanks @viguice for the hint

**Comment by good92** [comment]
Are you sure?
https://demo11.metadatatechnology.com/FusionRegistry/webservice/data.html

https://demo11.metadatatechnology.com/FusionRegistry/sdmx/v2/data/dataflow/ESTAT/ACF_D_LO1/1.0/?format=sdmx-compact-2.1

**Comment by viguice** [comment]
@good92, Fusion Registry v11 implements SDMX 3.0 (v2 is the latest version of the API). You can find the documentation [here](https://wiki.sdmxcloud.org/Data_Query_Web_Service). I agree that is confusing to have versioning on the API and on the SDMX standard.
You can see that is using the latest version of the API by selecting a subset (clicking on some available codes). You will notice that the app by adding codes as parameters and not by modifying the path:
https://demo11.metadatatechnology.com/FusionRegistry/sdmx/v2/data/dataflow/ESTAT/ACF_D_LO1/1.0/?c[geo]=BE&format=sdmx-compact-2.1
However, all possible filtering are not yet supported. For example, the following URL should in principle return data for all countries starting by B (Belgium and Bulgaria) but it is not working.
So, the work is ongoing on the new API is not yet fully supported. Nevertheless, the main features are accessible and it is sufficient for preparing SDMX connector to future v3 providers.
For this particular website, I don't know how long it will stay like this. As Metadata Technology has been acquired by Regnology recently, I expect that it will be shutdown soon or later (or transferred to a new URL).

**Comment by amattioc** [comment]
I edited the title of this issue. For now we only focus on the new version of the REST API (2.0.0). The support for structure and data messages will stay on v2.1.

**Comment by amattioc** [comment]
fixed 2c32212130b9e40daf2887330458cc8ee275136e
