### ISSUE TITLE
Error "Attribute name "async"

### ISSUE THREAD

**Issue by giannilmbd** [amattioc/SDMX#239]
Hi,
Running this code
df.imf.usGDP <- RJSDMX::getTimeSeriesTable('IMF2', 'DS-IFS_2023M05/Q..NGDP_NSA_XDC');
I sometimes get the following error message. But not always or systematically. Any clue?
Thanks
Gianni

> Error in .jcall("RJavaTools", "Ljava/lang/Object;", "invokeMethod", cl,  : 
  it.bancaditalia.oss.sdmx.exceptions.SdmxXmlParsingException: Error detected while parsing SDMX response: ParseError at [row,col]:[5,16]
Message: Attribute name "async" associated with an element type "script" must be followed by the ' = ' character.

**Comment by amattioc** [comment]
Hi @giannilmbd , we get the same in our nightly tests, from time to time. Probably the provider returns http 200 and an HTML error page in some cases (and then we fail the parsing). I don't think we can do anything unfortunately.

**Comment by giannilmbd** [comment]
I see. Anyway, it works most of the time:-)
Thanks
