### ISSUE TITLE
getFlows('IMF') not working.

### ISSUE THREAD

**Issue by Analect** [amattioc/SDMX#24]
> getFlows('IMF')
Error in .jcall("RJavaTools", "Ljava/lang/Object;", "invokeMethod", cl,  : 
  it.bancaditalia.oss.sdmx.util.SdmxException: Connection failed. HTTP error code : 404, message: Not Found
SDMX meaning: No results matching the query.

It appears this web-services query from the SDMX Helper Tool no longer works:
http://sdmxws.imf.org/RestSDMX2/sdmx.ashx/GetKeyFamily/ALL

This link seems to suggest no RESTful way of obtaining this list.
http://sdmxws.imf.org/Gateway/Help.aspx

Any thoughts on how to get this?  Thanks.

**Comment by amattioc** [comment]
Hi, yes I noticed it has started failing on Jan 15th. 

I sent a note to the IMF support about that. I'll keep you posted.

**Comment by Analect** [comment]
@amattioc Thanks.

**Comment by amattioc** [comment]
Hi @Analect I 've got news about this issue. There is a new enpdoint for the IMF web services, all info can be retrieved at 

http://sdmxws.imf.org/Gateway/Help.aspx.  

The fix will be available soon and it'll be integrated in the forthcoming version 1.3 of the connectors.

Cheers, Attilio

**Comment by amattioc** [comment]
Fixed in 3ae015534f6c8bd6076e04fbf3215327e3bb2ae4
