### ISSUE TITLE
updatedAfter support

### ISSUE THREAD

**Issue by Analect** [amattioc/SDMX#25]
I was wondering if RJSDMX has the possibility of handling sdmx queries with a updatedAfter parameter? I haven't been able to find any worked examples.
Does it require that the publisher is already using version 2.1 of SDMX? The link below is a replica of section 7 of the official SDMX standards, which suggests that you should be able to run a query that just returns the deltas since the last query ... any new INSERTS, UPDATES and DELETES. 
https://github.com/sdmx-twg/sdmx-rest/blob/master/v2_1/ws/rest/docs/4_4_data_queries.md

As a use-case, today's IMF global growth revisions - could a query into their REST service effectively return just those values that have been revised, if you used the last forecast date as 'updatedAfter' parameter.

Thanks for your insight.

**Comment by amattioc** [comment]
Hi, the updatedAfter parameter is supported by the ECB provider. Try:

getSDMX('ECB', 'EXR.A.USD.EUR.SP00.A?updatedAfter=2014-12-15T14%3A15%3A00%2B01%3A00')

but I'm not sure about the other ones, as I did not find any documentation about it.

Cheers

**Comment by Analect** [comment]
@amattioc . Sorry, I was going to close this out, but I had a follow-up question.  I was looking for another time-series where there are regular revisions, so I've used HICP and also added a 'includeHistory' parameter. The output from the getSDMX is below, from what is effectively this URL: https://sdw-wsrest.ecb.europa.eu/service/data/ICP/M.U2.N.000000.4.ANR?updatedAfter=2014-01-01T14%3A15%3A00%2B01%3A00&includeHistory=True

It takes some time to process, since I presume it is looping through various parses. The output format isn't altogether intuitive, since it doesn't include some of the contextual fields pertaining to the data items, such as 'action', 'validFromDate', 'OBS_STATUS', 'OBS_CONF' and 'OBS_COM'.  Is there any way for me to specify these a fields to be returned from a getSDMX call?

Thanks for your insights.

getSDMX('ECB', 'ICP.M.U2.N.000000.4.ANR?updatedAfter=2014-01-01T14%3A15%3A00%2B01%3A00&includeHistory=TRUE')
Jan 22, 2015 10:34:14 AM it.bancaditalia.oss.sdmx.client.SdmxClientHandler getFlow
INFO: Dataflow ICP not cached. Call Provider.
Jan 22, 2015 10:34:14 AM it.bancaditalia.oss.sdmx.client.RestSdmxClient runQuery
INFO: Contacting web service with query: http://sdw-wsrest.ecb.europa.eu/service/dataflow/all/ICP/latest
Jan 22, 2015 10:34:15 AM it.bancaditalia.oss.sdmx.client.SdmxClientHandler getDataFlowStructure
INFO: DSD for ECB/ECB_ICP1/1.0 not cached. Call Provider.
Jan 22, 2015 10:34:15 AM it.bancaditalia.oss.sdmx.client.RestSdmxClient runQuery
INFO: Contacting web service with query: http://sdw-wsrest.ecb.europa.eu/service/datastructure/ECB/ECB_ICP1/1.0
Jan 22, 2015 10:34:15 AM it.bancaditalia.oss.sdmx.client.RestSdmxClient runQuery
INFO: Contacting web service with query: http://sdw-wsrest.ecb.europa.eu/service/data/ECB,ICP,1.0/M.U2.N.000000.4.ANR?updatedAfter=2014-01-01T14%3A15%3A00%2B01%3A00&includeHistory=TRUE
$ICP.M.U2.N.000000.4.ANR
Dec 2013 
     0.8 

$ICP.M.U2.N.000000.4.ANR
 Nov 2013  Dec 2013 
0.8585902 0.8469501 

$ICP.M.U2.N.000000.4.ANR
Jan 2014 
     0.7 

$ICP.M.U2.N.000000.4.ANR
 Dec 2013  Jan 2014 
0.8469501 0.7780756 

$ICP.M.U2.N.000000.4.ANR
Feb 2014 
     0.8 

$ICP.M.U2.N.000000.4.ANR
 Jan 1996  Mar 1996  Apr 1996  Jun 1996  Jul 1996  Sep 1996  Oct 1996  Dec 1996 
2.3736694 2.3665049 2.3616326 2.1469063 2.1469063 2.0442520 2.0300300 1.9281437 
 Jan 1997  Mar 1997  Apr 1997  Jun 1997  Jul 1997  Sep 1997  Oct 1997  Jan 2014 
2.0198398 1.6004742 1.3014671 1.3933168 1.4995867 1.5908555 1.4951731 0.7780756 
 Feb 2014 
0.7149625 

$ICP.M.U2.N.000000.4.ANR
Mar 2014 
     0.5 

$ICP.M.U2.N.000000.4.ANR
 Feb 2014  Mar 2014 
0.7149625 0.4682046 

$ICP.M.U2.N.000000.4.ANR
Apr 2014 
     0.7 

$ICP.M.U2.N.000000.4.ANR
Jan 2001 Oct 2006 
2.009483 1.564047 

$ICP.M.U2.N.000000.4.ANR
 Mar 2014  Apr 2014 
0.4682046 0.7157464 

$ICP.M.U2.N.000000.4.ANR
May 2014 
     0.5 

$ICP.M.U2.N.000000.4.ANR
 Apr 2014  May 2014 
0.7157464 0.4936590 

$ICP.M.U2.N.000000.4.ANR
Jun 2014 
     0.5 

$ICP.M.U2.N.000000.4.ANR
May 2014 Jun 2014 
0.493659 0.501658 

$ICP.M.U2.N.000000.4.ANR
Jul 2014 
     0.4 

$ICP.M.U2.N.000000.4.ANR
 Jun 2014  Jul 2014 
0.5016580 0.3761005 

$ICP.M.U2.N.000000.4.ANR
Aug 2014 
     0.3 

$ICP.M.U2.N.000000.4.ANR
 Jul 2014  Aug 2014 
0.3761005 0.3670821 

$ICP.M.U2.N.000000.4.ANR
Sep 2014 
     0.3 

$ICP.M.U2.N.000000.4.ANR
 Aug 2014  Sep 2014 
0.3670821 0.3143318 

$ICP.M.U2.N.000000.4.ANR
Oct 2014 
     0.4 

$ICP.M.U2.N.000000.4.ANR
 Sep 2014  Oct 2014 
0.3143318 0.3827833 

$ICP.M.U2.N.000000.4.ANR
Nov 2014 
     0.3 

$ICP.M.U2.N.000000.4.ANR
 Oct 2014  Nov 2014 
0.3827833 0.2809228 

$ICP.M.U2.N.000000.4.ANR
Dec 2014 
    -0.2 

$ICP.M.U2.N.000000.4.ANR
  Nov 2014   Dec 2014 
 0.2809228 -0.1611809

**Comment by amattioc** [comment]
@Analect Hi, I just opened issues #28 and #29 for tracking the missing attributes you found, thanks.

Regarding the updatedAfter and includeHistory parameters, i think they are not in the scope of the getTimeseries function (as it is intended today). The present getTimeseries' goal is to retrieve the 'current' version on the time series for data processing. For this reason the implementation has not included all the information that would be needed for processing revisions (e.g. info about abservations to be removed, validity times etc.). 

Anyway I think some new function that addresses the processing of revisions and vintage could be of interest, especially in the perpective of being used in ETL (like) processes. You may want to open an enhancement request, and I'll try and look into it.

Cheers, Attilio

**Comment by Analect** [comment]
@amattioc Added an 'enhancement' request, #30,  on your suggestion. I don't think I have the ability to assign the relevant label though. Thanks again.
