### ISSUE TITLE
SDMX

### ISSUE THREAD

**Issue by r-c-vincent** [amattioc/SDMX#265]
I tried to reinstall SDMX, but I am having issues with the java. Could you kindly advise? 

![getdatacodes](https://github.com/user-attachments/assets/8201a5b0-7219-43f7-9995-5a423598fc97)

**Comment by vpinna80** [comment]
Hi @r-c-vincent,
`getdatacodes` isn't a command developed by us.
You should directly contact the author of the command in question.
This should be the link: https://ideas.repec.org/c/boc/bocode/s458093.html

**Comment by r-c-vincent** [comment]
Thanks for your reply. I am fully aware of that. Last year, I updated the
SDMX to the one from your GitHub, and everything run smoothly. This time, I
am getting the bug displayed above. Do you have any advice?

**Comment by amattioc** [comment]
Hi, looking at the code it seems that **getdatacodes** is equivalent to the original **sdmxHelp**

Could you try that one? Please update the overlapping ado files with the ones in our release before trying

**Comment by r-c-vincent** [comment]
Hi, thanks for your prompt reply. I get the same error message (r(5100))
when typing "*sdmxHelp"*

**Comment by amattioc** [comment]
Hi think there is still some old file in your adopath. Let's start from a clean situation:

1. get rid of all the sdmx related directories
2. download v.3.4.0
3. adopath ++ to the 3.4.0 directory

try again, **getTimeSeries** and **sdmxHelp** should be fine....

**Comment by amattioc** [comment]
Hi @r-c-vincent any updates on this?

**Comment by amattioc** [comment]
Hi, please reopen this issue if you.need further help.

**Comment by r-c-vincent** [comment]
Hi. Thank you.
The issue was solved but I am having the same error message following the
SDMX update two weeks ago. Do you perhaps have any insights? Please see
message below.

[image: image.png]
