### ISSUE TITLE
Small mistake in SDMX/STATA /initSDMX.ado

### ISSUE THREAD

**Issue by econcz** [amattioc/SDMX#268]
`capture findfile SDMX.jar`
...
`java, shared(BItools): /cp 'r(fn)'`
does not work if the path is relative on MacOS/Linux, i.e., begins with "~"

`java, shared(BItools): /cp SDMX.jar`
works well.

Thank you for your work!

**Comment by amattioc** [comment]
Hi @econcz you are right, thanks for the hint.
