### ISSUE TITLE
possibility of 'getSDMXDelta' function for usage in an ETL system 

### ISSUE THREAD

**Issue by Analect** [amattioc/SDMX#30]
@amattioc As per your suggestion in #25, having a dedicated function to deriving relevant metadata and data from a SDMX query that specifies 'updatedAfter' and 'includeHistory' parameters.  In #25 I highlight the absense of any contextual metadata being returned from a query that includes these parameters.  The use-case is mainly for a system that is looking for the latest changes to a dataset that have been applied since a previous query (set as the updatedAfter base date).

There is some relevant discussion on the implementation of these here: https://github.com/sdmx-twg/sdmx-rest/pull/17

In conjunction with the data values, a user might specify what other meta-data pertaining to those values should be returned.  Perhaps as a default, it would include the following:
 'action', 'validFromDate', 'OBS_STATUS', 'OBS_CONF' and 'OBS_COM'.

Perhaps others have additional ideas.

Thanks. Colum

**Comment by amattioc** [comment]
Hi @Analect 

in a1d91daea04456f894951e838afc26b6ee609c19 I added a new R function (**getTimeSeriesRevisions**) that should make it possible to handle time series revision history as you were describing it. 
The *action* and *validity* attributes are managed too.

I'll be happy to have your feedback.

Best, Attilio

**Comment by amattioc** [comment]
no feedback, close.

**Comment by Analect** [comment]
Apologies @amattioc. Snowed under. I'll take a look at this later this week and come back to you.

**Comment by amattioc** [comment]
Hi @Analect no problem, take your time. If necessary, feel free to reopen the issue...

**Comment by Analect** [comment]
@amattioc

**Comment by amattioc** [comment]
Hi, the attributes you are looking for are set at time series level:

`> attr(result$ICP.M.U2.N.000000.4.ANR, 'action')`
`[1] "Replace"`
`> attr(result$ICP.M.U2.N.000000.4.ANR, 'validFromDate')`
`[1] "2014-01-16T11:00:00.000+01:00"`

Probably the dataframe form is more suitable for this kind of results:

`> resultDF = sdmxdf(result, meta=T)`
`> resultDF`
`                        ID     TIME        OBS ...                           ...   action      validFromDate                              ...`
`1  ICP.M.U2.N.000000.4.ANR nov 2013  0.8585902     ...   Replace   2014-01-16T11:00:00.000+01:00...`
`2  ICP.M.U2.N.000000.4.ANR dic 2013  0.8469501      ...   Replace   2014-02-24T11:03:43.000+01:00...`
`3  ICP.M.U2.N.000000.4.ANR gen 2014  0.7780756     ...   Replace   2014-03-17T11:47:08.000+01:00...`
`...`

Best, Attilio

**Comment by Analect** [comment]
@amattioc 
Thanks for the explanation above.
Perhaps I'm not fully understanding the scope of the updatedAfter and includeHistory capabilities under the SDMX spec, or maybe I'm just not using the getTimeSeriesRevisions properly.

For instance, if I do a simple:
```
getTimeSeries('ECB','ICP.M.U2.N.000000.4.ANR')
```
 I get 291 observations.

and if I do:
```
getTimeSeriesRevisions('ECB','ICP.M.U2.N.000000.4.ANR',start='1990-01-01',end='2015-04-01', updatedAfter='1990-01-01', includeHistory=T)
```
I get 293 observations ... only an additional two observerations for February and March 2015.

I was under the impression that if I set updatedAfter sufficiently far back, then I would see substantially more observations over time, as preliminary estimates get 'replaced' with actual data, or as data gets 'revised', based on a change in methodology or something.

In addition, the setting the meta=T when converting to a DF, excludes important fields like OBS_COM.
```
<generic:Obs>
<generic:ObsDimension value="2008-01"/>
<generic:ObsValue value="3.209442981172561"/>
<generic:Attributes>
<generic:Value id="OBS_STATUS" value="A"/>
<generic:Value id="OBS_CONF" value="F"/>
<generic:Value id="OBS_COM" value="Introduction of methodological changes to the German HICP including - new basket, updated of volume structure of the weights, introduction of explicit weights for outlets and implementation of regulation (EC) No 701/2006 on the temporal coverage of price collection in the HICP"/>
</generic:Attributes>
</generic:Obs>
```
Am I missing something in terms of trying to capture how a data-series evolved over time by leveraging this SDMX functionality?

Thanks. Colum

**Comment by gplopez** [comment]
Hi, the 'updatedAfter' scope is to get only freshly updated data,
See also https://github.com/sdmx-twg/sdmx-rest/wiki/Tips-for-consumers#get-only-what-you-need

**Comment by amattioc** [comment]
Hi Colum, 

my interpretation of the **includeHistory** parameter is the same as yours. If you set it to true it will retrieve the **full history** of disseminations for the selected resource. It can be used independently from the **updatedAfter** parameter, but if they are used in combination you can decide the starting point of the history you want to retrieve. I also had a look at the raw XML of the example you pasted, and the contents match the results you see in R: 34 datasets (thus 34 time series) and 393 obs. The only revisions I see here are Feb 2015 and Mar 2015 that have been published twice. 

Unfortunately I don't know the ECB policy regarding the publication of estimates and revisions, but maybe it depends on the data flow...

Regarding the **OBS_COM** attribute, you are right, it's a bug and it impacts all the observation level attributes (with the exclusion of STATUS). It is already tracked in #28 .

I hope it helps, Attilio

**Comment by Analect** [comment]
@amattioc 
I've emailed 'statistics@ecb.europa.eu' to try to get clarification.
Don't mean to labour the issue, but another example where there are inconsistencies:

On https://github.com/sdmx-twg/sdmx-rest/wiki/Data-queries, there are various examples. I modified the third example to add 'includeHistory=true'

```
http://a-sdw-wsrest.ecb.int/service/data/EXR/M.USD+GBP+JPY.EUR.SP00.A?updatedAfter=2009-05-15T14%3A15%3A00%2B01%3A00&includeHistory=TRUE
```

Using RJSDMX, I get back a dataframe with 550 observations. Note, I'm ensuring the ISO 8601 timestamp is percent-encoded, as per the sdmx-twg docs.

```
result_exr <- getTimeSeriesRevisions('ECB','EXR.M.USD+GBP+JPY.EUR.SP00.A', updatedAfter='2009-05-15T14%3A15%3A00%2B01%3A00', includeHistory=TRUE)
resultDF_exr <- sdmxdf(result_exr,meta=T)
```

If I repeat the same exercise, using the 'rsdmx' package, I get back 586 observations, where there appears to be two observations per month going back for a one year period (ie. from April 2014) ... but where those observations values are identical (ie. no change) in both cases.

```
> library(rsdmx)
> myURL <- "http://a-sdw-wsrest.ecb.int/service/data/EXR/M.USD+GBP+JPY.EUR.SP00.A?updatedAfter=2009-05-15T14%3A15%3A00%2B01%3A00&includeHistory=TRUE"
> dataset <- readSDMX(myURL)
> stats <- as.data.frame(dataset)
> View(stats)
```

Is the RJSDMX package rejecting the additional 36 observations from the XML file on the basis that the value is unchanged?

Admittedly, EXR is perhaps not the best dataflow to do these experiments on, given that observations are presumably less likely to have initial estimates that then get 'replaced'.

**Comment by amattioc** [comment]
Hi, it took me a while to understand what was going on, but I think I got it. 

The web service endpoint that you are using with RSDMX (http://a-sdw-wsrest.ecb.int) is probably a wrong one. The correct one is: http://sdw-wsrest.ecb.europa.eu/ 

You can check it here: https://github.com/sdmx-twg/sdmx-rest/wiki/Where-is-it-used#ecb

If you use the correct endpoint, things should get aligned. You can try this simplified query in a browser to see the differences:

**WRONG**
http://a-sdw-wsrest.ecb.int/service/data/EXR/M.USD.EUR.SP00.A?updatedAfter=2009-05-15&includeHistory=TRUE&startPeriod=2014-04&endPeriod=2014-04

**CORRECT**
http://sdw-wsrest.ecb.europa.eu/service/data/EXR/M.USD.EUR.SP00.A?updatedAfter=2009-05-15&includeHistory=TRUE&startPeriod=2014-04&endPeriod=2014-04

Let me know, Attilio

**Comment by Analect** [comment]
@amattioc 
Sorry about that. I guess 'http://a-sdw-wsrest.ecb.int' is being used as a 'test' end-point in the sdmx-twg docs ... and I had been using some of their examples to try to understand this stuff a bit better!

**Comment by amattioc** [comment]
Hi, no problem. I'm happy it was not a bug.

**Comment by Analect** [comment]
@amattioc 
Just for completeness in case others reference this thread. It appears, having emailed the ECB, that the updatedAfter/includeHistory are only implemented on the RTD dataflow at present.

Here is a basic working example with a dataset from that dataflow ... the first including historical observations, the second not.

Returns 15 observations:
```
http://sdw-wsrest.ecb.europa.eu/service/data/RTD/M.S0.N.P_C_OV.A?updatedAfter=2014-04-01&includeHistory=TRUE&startPeriod=2014-04&endPeriod=2015-04
```
and this returns 8 observations:
```
http://sdw-wsrest.ecb.europa.eu/service/data/RTD/M.S0.N.P_C_OV.A?updatedAfter=2014-04-01&includeHistory=FALSE&startPeriod=2014-04&endPeriod=2015-04
```
There's not much transparency in terms of which of the statistical bodies have implemented this feature and, where they have, to which dataflows they have applied it. It would be great if someone with involvement in that process that has this information might add it to your repo wiki.

I can at least add the ECB/RTD info somewhere. Let me know if you would like me to do this.

**Comment by amattioc** [comment]
Hi, I'm not sure this project is the best place for this kind of information. Furthermore the landscape is very changing and all information that are not directly maintained by the institution that supports the web service risk to become rapidly outdated. 

Anyway I strongly agree that having these detailed information in a common place would be of great help for all the SDMX community.

I'll let you know if I can think of something...

**Comment by amattioc** [comment]
@Analect I just saw https://github.com/sdmx-twg/sdmx-rest/issues/27 and I think this is absolutely the best place to have this info. Thanks for the suggestions.

Attilio
