### ISSUE TITLE
Add support of multilingual codes

### ISSUE THREAD

**Issue by charphi** [amattioc/SDMX#34]
SDMX is designed to support multiple languages but the current client only retrieve one (english or first).
Here is a link to an example : http://stat.nbb.be/restsdmx/sdmx.ashx/GetDataStructure/CAPSTOCK2010

**Comment by amattioc** [comment]
Hi, what about if I provide a new conf key in the properties file that, if set, overrides english as the preferred language? This way the mechanism will remain almost unchanged.

**Comment by charphi** [comment]
That would be ok.
The only need I have is to be able to change that property by code (by using Configuration#setDefaultLang(String) for example) so that the user would have the possibility to choose its preferred language inside the application.

**Comment by amattioc** [comment]
Do you need the setDefaultLanguage to be just in the java lib or do you need it in the tools as well?

**Comment by charphi** [comment]
Just in the java lib.

**Comment by amattioc** [comment]
It should be available at revision 005ff6babbd2bd5f2665953e9e1887feb1cca360

You can use either the new configuration key **sdmx.lang** in the properties file (e.g. sdmx.lang=fr ) or the new **SdmxHandler** method **setPreferredLanguage**.

The default is English and works as before.

Let me know if it works as you expected...

**Comment by charphi** [comment]
I've just tested it and it works perfectly.
Thank you very much !
