### ISSUE TITLE
ABS client broken

### ISSUE THREAD

**Issue by charphi** [amattioc/SDMX#39]
The rest client for ABS seems broken.
The following query doesn't work anymore:
http://stat.abs.gov.au/restsdmx/sdmx.ashx/GetDataStructure/ALL/ABS

**Comment by amattioc** [comment]
Hi, I tried also other queries in ABS and they seem not to be working any longer: maybe the provider is in maintenance. If it doesn't get back, I'll try and contact the ABS support for checking what happened.

**Comment by amattioc** [comment]
I received an update about this: the provider is up and running again. 

Best, Attilio

**Comment by charphi** [comment]
Ok, thanks.
