### ISSUE TITLE
SDMXHelper2 - generic issue for tracking the evolution of the new helper

### ISSUE THREAD

**Issue by Tungurahua** [amattioc/SDMX#46]
For data providers with a large number of flows (e.g. Eurostat/ILO) it is almost impossible to find a specific flow as they are in random order. From a user perspective I could think of the following improvements:

- sort dataflows alphabetically by code
- display the dataflows in a grid that's sortable either by code or description. Display in a grid would although improve readability.
- Make the list of dataflows searchable

However, I don't know how difficult each of them would be to implement.

Using the package in R I think that `getProviders()` and `getFlows()` do a good job for identifying a dataflow or a group of dataflows. However, the selection of dimensions and codes is where a gui really comes in helpful. Thus another idea would be to allow the helper to accept a combination of data-provider / dataflow as input parameters. Something like `sdmxHelper(provider="EUROSTAT", flow="nrg105")` which would open the helper with this selection set.

**Comment by amattioc** [comment]
I fully agree. For now I added lexycographical ordering to flows and codes. (7de435a5642adde664b4053905341dab6e942f64)

**Comment by amattioc** [comment]
Starting from 90b30d3e65e24d35fd31b2224675f0fdc1cd549f the flows and codes are in a sortable table.

**Comment by Tungurahua** [comment]
Works like a charm! This makes the helper a big productivity-enhancer. I would prefer check-boxes instead of cmd-clicking to select multiple items as with long lists it's quite easy to loose overview. But that's a matter of taste.

As general side-note: I was wondering how you see the helper in the overall picture of the package. Do you plan to develop this into a full fledged, one-stop data browser for SDMX or is it rather intended as a helper function (as which it already serves me good and well). This would give me an indication about the level of scrutiny to apply in the review of the tool.

**Comment by gplopez** [comment]
Attilio, very nice. A label showing the selected provider could be useful.

**Comment by amattioc** [comment]
Gianpaolo, done in f52dd45a2f1a41af02574e1933e5918d738a8453 :-)

**Comment by amattioc** [comment]
@Tungurahua check-boxes are a good idea, but I'll keep it for later. Right now I'm focusing on row filtering. I think it would improve usability a lot...

Regarding the helper, we already use it independently from the data tools. Users can launch it with a command that we provide in our computational environments. I think that, for being a complete standalone application, it should also be able to retrieve the data...

**Comment by amattioc** [comment]
In 8e9cd4c7936e0f70867879ef70f7f6d8123c8bb7 I added flow filtering and a nice **checkQuery** function that lets you preview the content of the query you built. It has to be made better, but I think can be helpful.

Let me know.

**Comment by Tungurahua** [comment]
Great! This is helpful. I like that the log contains some information about the size of the dataset.

**Comment by Tungurahua** [comment]
However, there is an issue with entering text into the search-box. The cursor happens to stay to the left of the entered character, it doesn't accept backspace etc. This happens both under Windows and OSX.

**Comment by Tungurahua** [comment]
BUG
Also selecting codes for a second dimension will erase the codes selected in the prior dimension.

**Comment by amattioc** [comment]
Selection bug fixed in dd31ec6df5a795a6370833121c435773167aad08. Thanks

**Comment by amattioc** [comment]
Multithreading and query results panel in 50f16e48

**Comment by amattioc** [comment]
Hi @Tungurahua 

in c40bdb1382d576366f1561ce1c31791640bf8962 I fixed the problem with special characters that you found. Can you please check?

Best.

**Comment by Tungurahua** [comment]
Are you referring to #40? Yes, that's all Silvester. A

**Comment by Tungurahua** [comment]
I mean it's solved. Never write from a phone. A

**Comment by amattioc** [comment]
Hi
no I was referring to 

"BUG
However, there is an issue with entering text with special characters into the search-box. For example, when entering an asterisk *, the cursor happens to stay to the left of the entered character, it doesn't accept backspace etc."

Thanks

**Comment by Tungurahua** [comment]
Yes, that's  also solved! Thanks a lot!

**Comment by amattioc** [comment]
OK, very well. I'll close this issue as the main development phase for helper2 is done.
