### ISSUE TITLE
minor enhancement of Wiki

### ISSUE THREAD

**Issue by Tungurahua** [amattioc/SDMX#47]
On the RJSDMX Wiki page the `install_github()` command should be changed from
   
    install_github(repo = "SDMX", username = "amattioc", subdir = "RJSDMX")

to 

    install_github(repo = "amattioc/SDMX", subdir = "RJSDMX")

as the username parameter has been depracated. 

This is a clearly minor issue and filing an issue somewhat excessive. What would be your suggestion for reporting textual changes in the Wiki? I am still new to git / github and do not know yet how to address these things properly in the given framework.

**Comment by amattioc** [comment]
Done.

Using an issue is quite fine for me. Thanks.
