### ISSUE TITLE
sdmxHelp() does not clear dimensions when moving to unretrievable dataflow

### ISSUE THREAD

**Issue by Tungurahua** [amattioc/SDMX#52]
If you switch from a functioning dataflow1 to a erroneous dataflow2 the "Select Dimensions" retains the "Select Dimensions" of dataflow1. The field should be empty instead.
To illustrate the behaviour, select Eurostat as provider, sort Code ID alphabetically and change the code ID from `sts_trtugr_q` to `t2020_10`. As you can see in the following screenshots, the Code at the beginning of the REST-ID stays unchanged as well as the content of the "Select Dimensions" box.

Note that `t2020_10` returns a server 404 error which seems to be due to an error at Eurostat that relates to all `t2020` indicators at the moment. The behavior will not be reproducable if the server is reachable again.

Graying out Dimensions and Code selection boxes if server is unreachable would be a great feat.

![screen shot 2015-03-24 at 21 29 18](https://cloud.githubusercontent.com/assets/2544688/6812129/14d54b04-d26d-11e4-810b-e6a74b17a27a.png)
![screen shot 2015-03-24 at 21 30 27](https://cloud.githubusercontent.com/assets/2544688/6812128/14d2ae08-d26d-11e4-8ebd-abb228faf816.png)

**Comment by Tungurahua** [comment]
I bcc'ed you in a bug-report to Eurostats SDMX-department. Please let me know if you would like to be included in such conversation or if you would prefer to be excluded (we all receive too much emails ;-))
Best
Albrecht

**Comment by amattioc** [comment]
No problem, you can keep me in the loop

**Comment by amattioc** [comment]
fixed in 5dd38b9781afe5633e0c8105cafd4eac37cb240d
