### ISSUE TITLE
Change Code ID and Code Description to Flow ID and Flow Description in sdmxHelp2()

### ISSUE THREAD

**Issue by Tungurahua** [amattioc/SDMX#53]
In the helper tool the topmost table reads `Code ID` and `Code Description`.  I would suggest to change this to  `Flow ID` and  `Flow Description` to have a consistent wording (-> Codes are the variable levels of the dimensions)

**Comment by amattioc** [comment]
This should be fixed in 8e9cd4c7936e0f70867879ef70f7f6d8123c8bb7
