### ISSUE TITLE
How to un-select a dimension?

### ISSUE THREAD

**Issue by Tungurahua** [amattioc/SDMX#55]
Is there a way to un-select a dimension? Once I have selected e.g. an annual frequency, the only way to clear the frequency dimension is to select another data flow. The expected behaviour would be that `Ctrl + Click` not only clears the selection field but also the selection in the REST-ID. This does not work if a single item is to be de-selected. This is especially cumbersome when working with WB indicators as they do not distinguish individual indicators by FlowID but by the `SERIES` dimension.

See example below:

Annual frequency selected turns up in REST-ID
![snip01](https://cloud.githubusercontent.com/assets/2544688/6919140/c332fa6a-d7b4-11e4-801b-147ba6f85aff.PNG)

Annual frequency de-selected does not clear in REST-ID
![snip02](https://cloud.githubusercontent.com/assets/2544688/6919142/c90fe466-d7b4-11e4-872a-fa863e52ff3f.PNG)

**Comment by amattioc** [comment]
wrong fix

**Comment by amattioc** [comment]
Hi, it should be fixed in f8b5ef6cc249986977932791b7f3cf5ce9ff5089

I also modified the model so that the code selections are retained by the ui. It should be more usable.

Best, Attilio

**Comment by Tungurahua** [comment]
Hmm, beginning  with 6aca2dfdb8b164c026c27ad8678af69be266979a I cannot connect to the providers anymore. The "executing query" window shows up for a brief moment, but disappears before the dataflows of the selected provider show up.

**Comment by amattioc** [comment]
Hi, sorry I had introduced a bug in default proxy handling that showed up only in no proxy environments...

It should be fixed in 43e4b30648204d5cc7b3f8f7a97cfddb2ee0868e

**Comment by Tungurahua** [comment]
And it is fixed indeed!
Thanks!
