### ISSUE TITLE
Selecting Value for FREQ or REF_AREA dimension renders Worldbank IDs invalid

### ISSUE THREAD

**Issue by Tungurahua** [amattioc/SDMX#56]
With Worldbank as provider, it  is possible to create valid queries only as long as no selection for `FREQ` or `REF_AREA` has been carried out. For example testing the query `WDI/.BX_KLT_DINV_WD_GD_ZS.` identifies 248 time series while `WDI/.BX_KLT_DINV_WD_GD_ZS.GBR` returns an error. 

I don't know if this is a problem with the World bank (Beta provider) or if this is related to RJSDMX.

**Comment by amattioc** [comment]
Hi, yes you're right. The WB has a very peculiar way of building the query. I'll try and think to a workaround...

**Comment by amattioc** [comment]
In b5a877744cbbaf0198e7f351930122153af60f75 I added an adapter for the WB data queries. Now it is possible to handle them as a standard SDMX query.

You can check the difference comparing, in the new command window, the tool commands with the URL.

Anyway the + for keys does not work in this provider. Only full wildcard.

**Comment by amattioc** [comment]
Feel free to reopen if necessary. Best

**Comment by Tungurahua** [comment]
Great, works now.
