### ISSUE TITLE
Point-click execution of the SDMXhelper

### ISSUE THREAD

**Issue by Tungurahua** [amattioc/SDMX#58]
If technically possible it  would be great if the `SDMXhelper` could be started directly by clicking on `SDMX.jar` without specifying the classpath. This would allow to distribute the application easily to users not comfortable with the command prompt under Window. 

In principle it is possible to create a shortcut that includes the command line arguments, but this requires the file to be stored in a specific location.

**Comment by amattioc** [comment]
Nice one, and pretty easy probably....

**Comment by amattioc** [comment]
Done in 07a1e2b03973d5f0eb92942d53cb4c92e1805a70

To execute by double-click you have to associate the .jar extension with java, check http://stackoverflow.com/questions/8511063/how-to-run-jar-file-by-double-click-on-windows-7-64

**Comment by Tungurahua** [comment]
Great! Works as expected. The app starts both from R and by couoble-clicking.

Thx
A
