### ISSUE TITLE
Default proxy

### ISSUE THREAD

**Issue by amattioc** [amattioc/SDMX#6]
Handle a new conf key for default proxy, useful with single proxy environments

**Comment by amattioc** [comment]
commit: 3ae015534f6c8bd6076e04fbf3215327e3bb2ae4

A default proxy can now be specified for all providers by means of the configuration key http.proxy.default.

The configuration file has been updated accordingly.

**Comment by masabbat** [comment]
Outside the proxy, RJSDMX works.
Inside the proxy (after configuring the proxyserver and proxyport), I receive the following message:

> my_ts=getSDMX('ECB','EXR.A.USD.EUR.SP00.A')
Error in .jcall("RJavaTools", "Ljava/lang/Object;", "invokeMethod", cl,  : 
  it.bancaditalia.oss.sdmx.util.SdmxException: Exception. Class: java.net.ConnectException .Message: Connection timed out: connect

**Comment by amattioc** [comment]
Hi, I think the connector is not reading the correct configuration file. Can you increase the trace level? You can put the following lines in the configuration file:

`SDMX.level = FINER`
`handlers= java.util.logging.ConsoleHandler`
`java.util.logging.ConsoleHandler.level = FINER`

let me know...

**Comment by amattioc** [comment]
Hi @masabbat any news on this?

Best, Attilio

**Comment by amattioc** [comment]
no feedback, close.
