### ISSUE TITLE
Add ' Help | About SDMX Helper Tool' Menue item

### ISSUE THREAD

**Issue by Tungurahua** [amattioc/SDMX#60]
It would be great if the current version of the SDMX helper tool could be queried from within the application. The normal place where I would search for this would be a menue item ' Help | About SDMX helper' that opens a window from which the current version (e.g. version number / git-sha) and other information (e.g. author, license, link to documentation on github) is available.

This will come in handy when checking bugs/behavior over the phone with other users.

**Comment by amattioc** [comment]
Hi Albrecht, I agree it can be useful. I'll have a look at how to implement it. Thanks for the hint.

Best, Attilio

**Comment by amattioc** [comment]
Hi @Tungurahua 

I added a help/about to the sdmx helper following your suggestion. This is how it looks like:

![snap](https://cloud.githubusercontent.com/assets/8512242/9304814/79ceef96-44ec-11e5-8424-50d80fd3296d.png)

A small difference is that I did not set the git hash, but the timestamp, for technical reasons. Anyway it is possible to link the timestamp of the helper to the github revision by means of the https://github.com/amattioc/SDMX/blob/master/BUILD file, that is updated at every git commit.

Feel free to reopen if you think anything is missing, and sorry for taking so long...

Best, Attilio
