### ISSUE TITLE
dates in reverse order - Matlab connector

### ISSUE THREAD

**Issue by tothmat** [amattioc/SDMX#62]
Data providers (e.g. Eurostat) sometimes return dates in reverse order (i.e. first date is the most recent). This together with function convert.m can result in counter-intuitive date ranges spanning e.g. from 2014 to 2060 in Matlab's timeseries format.

A small addition at line 92 in convert.m may solve this issue:
```
if datenum(arrayTimeSlots(2,:)) > datenum(arrayTimeSlots(1,:))
    ts.timeinfo.startdate = arrayTimeSlots(1,:);
else
    ts.timeinfo.startdate = arrayTimeSlots(end,:); 
end
```
rgds,
M

**Comment by amattioc** [comment]
Hi, good catch! :-)

Thanks a lot...

**Comment by amattioc** [comment]
Hi @tothmat I fixed the issue in commit 4bb8f868bae0ae6e926f147e6854595c172173f9
I preferred to do it in the java layer so that all connectors can receive results that are coherently ordered by date. 

Can you please check that it works now? Thanks again for spotting this.

Attilio

**Comment by tothmat** [comment]
Hi Attilio,
Seems to be working, good job!

Best,
Máté

**Comment by amattioc** [comment]
Great.

Cheers, Attilio
