### ISSUE TITLE
OECD 500 error

### ISSUE THREAD

**Issue by pdgilbert** [amattioc/SDMX#80]
(this is probably a provider side issue but I am putting it here to keep track.)

These requests fail in RJSDMX on OECD 
>   tts <-  getSDMX('OECD', 'QNA.CAN.PPPGDP.CARSA.Q')
Error in .jcall("RJavaTools", "Ljava/lang/Object;", "invokeMethod", cl,  : 
  it.bancaditalia.oss.sdmx.util.SdmxException: Connection failed. HTTP error code : 500, message: Internal Server Error
SDMX meaning: Error on the provider side.
> 
>   tts <-  getSDMX('OECD', 'QNA.USA.PPPGDP.CARSA.Q')
Error in .jcall("RJavaTools", "Ljava/lang/Object;", "invokeMethod", cl,  : 
  it.bancaditalia.oss.sdmx.util.SdmxException: Connection failed. HTTP error code : 500, message: Internal Server Error
SDMX meaning: Error on the provider side.
> 
> tts <-  getSDMX('OECD', 'QNA.CAN+USA+MEX.PPPGDP.CARSA.Q')
Error in .jcall("RJavaTools", "Ljava/lang/Object;", "invokeMethod", cl,  : 
  it.bancaditalia.oss.sdmx.util.SdmxException: Connection failed. HTTP error code : 500, message: Internal Server Error
SDMX meaning: Error on the provider side.
>

**Comment by amattioc** [comment]
Yes, it seems a provider error, but it strangely happens only on some dataflows. Maybe there's an update in progress.
I usually wait for some days, but if you are in a hurry you may want to contact the oecd.stat support.

**Comment by amattioc** [comment]
Everything's ok now... I close the issue.
