### ISSUE TITLE
WorldBank client currently broken.

### ISSUE THREAD

**Issue by charphi** [amattioc/SDMX#85]
I'm not able to get dataflows from WB:
`SEVERE: Connection failed. HTTP error code : 400, message: Bad Request`

I can't even find information about the SDMX api on their web site.
I wonder if the SDMX web service has been removed.

**Comment by amattioc** [comment]
Hi @charphi, you're right: it started on Jan. 6th and it affects all call types.

I asked for information about this problem to the World Bank. I'll keep you updated.

**Comment by siddhug** [comment]
Issue has been fixed

**Comment by siddhug** [comment]
My bad, it is still not fixed

**Comment by amattioc** [comment]
The API is ok now. Apparently the web services have been updated and they send compressed streams now, so they cannot be handled correctly by the client. 

Commit 1acf37b02820581873d7438b4d949787979955f4 fixes this issue.

Thanks a lot @charphi  and @siddhug for helping with this.
