### ISSUE TITLE
Upgrade to Java 7

### ISSUE THREAD

**Issue by charphi** [amattioc/SDMX#86]
Upgrading to Java 7 will bring this improvements:
- New language features that improve code readability and maintenance ([Strings in switch Statements](http://docs.oracle.com/javase/7/docs/technotes/guides/language/strings-switch.html), [The try-with-resources Statement](http://docs.oracle.com/javase/7/docs/technotes/guides/language/try-with-resources.html), ...)
- New APIs 
- Improved security
- Java 6 is no more publicly supported since April 2013
- Available on all platforms

[Java SE 7 Features and Enhancements](http://www.oracle.com/technetwork/java/javase/jdk7-relnotes-418459.html)

**Comment by amattioc** [comment]
Hi @charphi, I agree. 

I've been keeping some steps behind for avoiding to break the compatibility with older MATLAB and SAS versions that used an embedded 1.6 JRE. Anyway I think nowadays it's quite safe to migrate to Java 7 and it'll be probably done by the first half of 2016. 

I'll keep this issue open until the migration is completed.

**Comment by charphi** [comment]
Great news!
Have you any plan concerning Java 8?

**Comment by amattioc** [comment]
Hi, the latest versions of STATA, SAS and MATLAB today embed a 1.7 JVM. We make our plans according to that, in order to ensure the widest possible support...

**Comment by amattioc** [comment]
Done in 9e0efb5e85d11ea9882a2b3c232f7bd98948f503
