### ISSUE TITLE
Handle Eurostat large responses (error 413)

### ISSUE THREAD

**Issue by amattioc** [amattioc/SDMX#90]
Eurostat will send a 413 error if the size of the response exceeds a specific size. The response anyway is provided at a separate URL that is stated in the error message.
A specific recovery action can be coded in the Eurostat client (that will have to be created) for handling this situation.

**Comment by charphi** [comment]
Here is a link that returns this 413 error:
[http://ec.europa.eu/eurostat/SDMX/diss-web/rest/data/ESTAT,nama_gdp_c,1.0/A.MIO_EUR..](http://ec.europa.eu/eurostat/SDMX/diss-web/rest/data/ESTAT,nama_gdp_c,1.0/A.MIO_EUR..)

**Comment by amattioc** [comment]
Sometimes the response is so large that the provider sends a different error message:

*Query size exceeds maximum limit (1000000 entries).*

In this case the data is not sent at all. The user will need to reshape the query and make it smaller.
