### ISSUE TITLE
EUROSTAT

### ISSUE THREAD

**Issue by rshatfield** [amattioc/SDMX#95]
I getting the same issue as reported previously with OECD with EUROSTAT. Working ok last week, but this week, fatal errors:
Mar 16, 2016 12:50:20 PM it.bancaditalia.oss.sdmx.client.RestSdmxClient runQuery
INFO: Contacting web service with query: http://ec.europa.eu/eurostat/SDMX/diss-web/rest/dataflow/all/namq_10_gdp/latest
Mar 16, 2016 12:50:20 PM it.bancaditalia.oss.sdmx.client.RestSdmxClient runQuery
SEVERE: Connection failed. HTTP error code : 501, message: Not Implemented
SDMX meaning: Feature not supported.
Mar 16, 2016 12:50:20 PM it.bancaditalia.oss.sdmx.client.RestSdmxClient getDataflow
SEVERE: Exception caught parsing results from call to provider EUROSTAT
Error in .local(serIDs, con, ...) : 
  namq_10_gdp/Q.CP_MEUR.NSA.P3_S13.uk error: it.bancaditalia.oss.sdmx.util.SdmxException: Exception. Class: it.bancaditalia.oss.sdmx.util.SdmxException .Message: Connection failed. HTTP error code : 501, message: Not Implemented
SDMX meaning: Feature not supported.

**Comment by amattioc** [comment]
Hi @rshatfield, you're right.

It seems that, starting from this morning, the EUROSTAT web service is no longer able to handle the **all** keyword in the **agency id** slot. This means that the URL:

http://ec.europa.eu/eurostat/SDMX/diss-web/rest/dataflow/all/all/latest

does not work, while the URL

http://ec.europa.eu/eurostat/SDMX/diss-web/rest/dataflow/ESTAT/all/latest

works fine. 

I'll check with the ESTAT support if this is a desired behavior or a bug and I'll fix it accordingly.

Thanks for signalling it.

**Comment by amattioc** [comment]
Hi @rshatfield I just uploaded a temporary workaround. It should be enough to get up and running again, till there is a definitive fix.

**Comment by rshatfield** [comment]
Downloaded, sorted the usual rJava stuff and it worked great! thanks for quick response @amattioc

**Comment by charphi** [comment]
According to ESTAT, the web service has been updated recently:
> On March 16, a new version of the SDMX web services will be made available.
> This will impact  the operations GetStructureSpecificData for SOAP SDMX 2.1 and data for REST SDMX 2.1 (http://ec.europa.eu/eurostat/web/sdmx-web-services/sdmx)

The updated documentation specifies that:
> The AgencyID is always ESTAT and is a required field.
> (http://ec.europa.eu/eurostat/web/sdmx-web-services/rest-sdmx-2.1)

**Comment by amattioc** [comment]
Right. I received a response from the Eurostat support and they confirm that the **all** keyword is no longer supporter for the agency id.

The workaround remains as a definitive fix then.
