### ISSUE TITLE
Maven repository availability

### ISSUE THREAD

**Issue by andtorg** [amattioc/SDMX#98]
Hi @amattioc ,
I came across your java connector, and sdmx in general, while looking for a way to consume statistics webservices. Great tool. I would like to use it as a dependency in a small open source project. Is it available from a public maven repo?

**Comment by amattioc** [comment]
Hi @andtorg , I'm glad you like the project.

The java library is not published in a public maven repo and the official binary version is only in the **downloads section** of each release (https://github.com/amattioc/SDMX/releases)

Anyway, I think that your request could make users' life easier in some contexts, so I'll try and check if it is actually feasible. I'll leave the issue open for getting back to you with more feedback.

Best, Attilio

**Comment by andtorg** [comment]
Hi @amattioc,
thanks for considering the chance. Meanwhile I managed to use a git submodule and include it in a multi-module maven project. Not as easy as a straight dependency, but still quite comfortable. I'll let you know if I come up with anything interesting. 
Rgds

**Comment by amattioc** [comment]
Hi @andtorg , yes please keep me posted on the evolution of your project. I'm always curious about how the connectors are used.
Best, Attilio

**Comment by eivindveg** [comment]
Just posting to inform you that JitPack's Maven repository works for this repository, even though the pom.xml file is located in a subdirectory:

https://jitpack.io/#amattioc/SDMX/v1.6.2

**Comment by vpinna80** [comment]
Checked out and it works correctly. Thank you @eivindveg.

**Comment by amattioc** [comment]
Hi @andtorg, please check if this fits your needs. In case it doesn't, feel free to reopen.

Best, Attilio
